#!/bin/sh

# Java on MacOS is provided by Jetbrains Toolbox
export AS_PATH="${HOME}/Applications/Android Studio.app/Contents"
export JAVA_HOME="${AS_PATH}/jbr/Contents/Home/"
export GRADLE_LOCAL_JAVA_HOME="${JAVA_HOME}"

# Add Android tools to the PATH
PATH="${HOME}/devel/sdk/android/platform-tools:${PATH}"
PATH="${HOME}/devel/sdk/android/cmdline-tools/latest/bin:${PATH}"
# Kotlin tools
PATH="${AS_PATH}/plugins/Kotlin/kotlinc/bin:${PATH}"
export PATH

if [ "$1" = "--shell" ]; then
  shift
  exec bash "$@"
else
  # Launch Android Studio
  exec open "${HOME}/Applications/Android Studio.app" "$@"
fi
