#!/bin/sh

# Sometimes MacOS fucks the path by sourcing our PATH after the system path.
# Fix it by flipping the order

_flip() {
  _before=""
  _found=0

  _paths="$(printf -- '%s' "${PATH}" | tr ':' ' ')"
  _new_path=""
  for p in ${_paths}; do
    if [ "${_found}" -ne 0 ]; then
      if [ -z "${_new_path}" ]; then
        _new_path="${p}"
      else
        _new_path="${_new_path}:${p}"
      fi
      continue
    fi

    case "${p}" in
      "${HOME}"/*)
        _found=1
        if [ -z "${_new_path}" ]; then
          _new_path="${p}"
        else
          _new_path="${_new_path}:${p}"
        fi
        ;;
      *)
        if [ -z "${_before}" ]; then
          _before="${p}"
        else
          _before="${_before}:${p}"
        fi
        ;;
    esac
  done

  _new_path="${_new_path}:${_before}"

  printf -- 'export PATH="%s"\n' "${_new_path}"

  unset _before
  unset _after
  unset _paths
  unset _new_path

  return 0
}

main() {
  case "${PATH}" in
    /usr/local/bin:*)
      _flip || return 1
      ;;
    *)
      printf -- 'Path does not need flipping'
      return 1
      ;;
  esac

  return 0
}

main "$@" || exit 1
exit 0
