#!/bin/sh

if [ -d "${HOME}/Applications/PyCharm Community Edition.app" ]; then
  # Pycharm provided by Jetbrains Toolbox
  _py_path="${HOME}/Applications/PyCharm Community Edition.app"
else
  # Pycharm provided by Homebrew direct install
  _py_path="/Applications/PyCharm CE.app"
fi
export JAVA_HOME="${_py_path}/Contents/jbr/Contents/Home/"

# Add llvm to path
PATH="/opt/homebrew/Cellar/llvm@14/14.0.6/bin:${PATH}"
export PATH

if [ "$1" = "--shell" ]; then
  shift
  exec bash "$@"
else
  # Launch PYCharm
  exec open -a "${_py_path}" "$@"
fi

