#!/bin/sh

# Source our common library
. "/opt/pyamsoft/lib/container-launch"

NAME="scrutiny"
IMAGE="ghcr.io/starosdev/scrutiny"
TAG="1.31.1-omnibus"

CONTAINER_ENTRYPOINT="/entrypoints/init"

_prep_mounts() {
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/config" "/opt/scrutiny/config" || return 1
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/db" "/opt/scrutiny/influxdb" || return 1
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/logs" "/opt/scrutiny/logs" || return 1
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/entrypoints" "/entrypoints" || return 1

  # Needs udev from host
  _mount_bind "/run/udev" "/run/udev" "ro" || return 1

  return 0
}

_prep_caps() {
  # For smartctl
  _add_caps --cap-add SYS_RAWIO

  # Work with NVME
  _add_caps --cap-add SYS_ADMIN

  return 0
}

_prep_env() {
  return 0
}

_prep_network() {
  _network_isolate || return 1

  return 0
}

_prep_ports() {
  _add_ports -p "127.0.0.1:8081:8080/tcp"
  _add_ports -p "127.0.0.1:8086:8086/tcp"
  return 0
}

_check_user() {
  _require_root || return 1

  return 0
}

if _is_macos; then
  _elog 'Not supported on MacOS'
  exit 1
fi

main "$@" || exit 1
exit 0
