#!/bin/sh

# Splits up a user:path argument provided to a systemd instance unit
# and pass the expected format over to `tmpfs-mounter`
#
# Expected format is <user>:<escaped-path>[:options]

# Source our common library
# shellcheck source=/opt/pyamsoft/lib/common
. "${PYAMSOFT_PATH}/lib/common"

NAME="$(/bin/basename "$0")"

readonly VERSION="0.0.2"

main() {
  _cmd="$1"
  _instance="$2"

  if [ -z "${_cmd}" ]; then
    _elog '[%s] %s' "${NAME}" "${VERSION}"
    _elog 'Missing command, not forwarding to tmpfs-mounter %s' "${_instance}"
    _elog 'Expected format: "<user>:<escaped-path>[:escaped-options]"'

    unset _cmd
    unset _instance
    return 1
  fi

  if [ -z "${_instance}" ]; then
    _elog '[%s] %s' "${NAME}" "${VERSION}"
    _elog 'Missing instance, not forwarding to tmpfs-mounter %s' "${_instance}"
    _elog 'Expected format: "<user>:<escaped-path>[:escaped-options]"'

    unset _cmd
    unset _instance
    return 1
  fi

  case "${_instance}" in
  *:*)
    ;;
  *)
    _elog '[%s] %s' "${NAME}" "${VERSION}"
    _elog 'Invalid instance format, not forwarding to tmpfs-mounter %s' "${_instance}"
    _elog 'Expected format: "<user>:<escaped-path>[:escaped-options]"'
    unset _cmd
    unset _instance
    return 1
    ;;
  esac

  # Split the instance by colon
  # First found is the user
  # Everything else is path and options
  _user=${_instance%%:*}
  _rest=${_instance#*:}

  # Then split the rest into path and options
  # If options have embedded colons for path mounts, keep them
  case "$_rest" in
  *:*)
    _path=${_rest%%:*}
    _options=${_rest#*:}
    ;;
  *)
    _path=${_rest}
    _options=""
    ;;
  esac
  unset _rest

  if [ -z "${_user}" ] || [ -z "${_path}" ]; then
    _elog '[%s] %s' "${NAME}" "${VERSION}"
    _elog 'Invalid instance format, not forwarding to tmpfs-mounter %s' "${_instance}"
    _elog 'Expected format: "<user>:<escaped-path>[:escaped-options]"'
    unset _user
    unset _path
    unset _options
    unset _cmd
    unset _instance
    return 1
  fi

  # Fix the path
  _unescaped_path="$(/bin/systemd-escape --unescape -- "${_path}")"
  unset _path

  # Pass to tmpfs-mounter
  if [ -n "${_options}" ]; then
    # Fix the options
    _unescaped_options="$(/bin/systemd-escape --unescape -- "${_options}")"
    unset _options
    exec "${PYAMSOFT_PATH}/sbin/tmpfs-mounter" "${_cmd}" "${_unescaped_path}" "${_user}" "${_unescaped_options}"
  else
    unset _options
    exec "${PYAMSOFT_PATH}/sbin/tmpfs-mounter" "${_cmd}" "${_unescaped_path}" "${_user}"
  fi
}

main "$@" || exit 1
exit 0
