#!/bin/sh

# For gamescope, the following is needed
# --devices=all;shm; is needed for Steam overlay and Steam input
# --env SDL_VIDEODRIVER=x11 must be set on the flatpak itself, not just in this file.

# S3TC texture filtering
export force_s3tc_enable=true

# Ignore forced TearFree display sync
export vblank_mode=0

# Fix weird texture bugs
# https://github.com/Plagman/gamescope/issues/320
export AMD_DEBUG=nodcc
export RADV_DEBUG=nodcc

# Mangohud
# https://github.com/flightlessmango/MangoHud#hud-configuration
#
# We cannot export MANGOHUD=1 before gamescope as it will crash.
# We must use gamescope to run mangohud, and then use mangohud to run our command.
export MANGOHUD_CONFIG=fps,cpu_temp,gpu_temp,ram,font_size=12,fps_limit=75,gl_vsync=0,vsync=1

# For Proton-GE
# https://github.com/GloriousEggroll/proton-ge-custom#modification
export PROTON_HEAP_DELAY_FREE=1
export PROTON_USE_SECCOMP=1

# Vampire survivors needs to run with logs on Proton Experimental or it crashes with a Javascript Error
# https://steamcommunity.com/app/1675200/discussions/1/3273566073555640279/
if printf -- '%s' "$*" | grep -q 'Vampire Survivors'; then
  export PROTON_LOGS=1
fi

# gamescope
# https://github.com/Plagman/gamescope
#
# Run games in Fullscreen at the nested resolution (which should be shown as the only FS res)
# FSR is between 0 (max) and 20 (min) instead of 0-5. Default is 2 => 8
# NOTE: Shouldn't crash if the environment sets SDL_VIDEODRIVER=x11

# Normal gamescope options
gamescope_options="--nested-width 1280 --nested-height 720 \
--output-width 1920 --output-height 1080 \
--fsr-upscaling --fsr-sharpness 8 \
--adaptive-sync --immediate-flips \
--nested-refresh 75 --nested-unfocused-refresh 30"

# If we are running in steam, add --steam option, otherwise do not (causes weird window issues)
if [ "${FLATPAK_ID}" = "com.valvesoftware.Steam" ]; then
  # shellcheck disable=SC2086
  exec gamescope --steam ${gamescope_options} -- mangohud "$@"
else
  # shellcheck disable=SC2086
  exec gamescope ${gamescope_options} -- mangohud "$@"
fi
