#!/bin/sh

# For gamescope, the following is needed
# --devices=all;shm; is needed for Steam overlay and Steam input
# --env SDL_VIDEODRIVER=x11 must be set on the flatpak itself, not just in this file.

# S3TC texture filtering
export force_s3tc_enable=true

# Ignore forced TearFree display sync
export vblank_mode=0

# Mangohud
# https://github.com/flightlessmango/MangoHud#hud-configuration
#
# We cannot export MANGOHUD=1 before gamescope as it will crash.
# We must use gamescope to run mangohud, and then use mangohud to run our command.
export MANGOHUD_CONFIG=fps,cpu_temp,gpu_temp,ram,font_size=16,fps_limit=75,gl_vsync=0,vsync=1

# For Proton-GE
# https://github.com/GloriousEggroll/proton-ge-custom#modification
export PROTON_HEAP_DELAY_FREE=1
export PROTON_USE_SECCOMP=1

# Run the executable in a session
# NOTE: Shouldn't crash if the environment sets SDL_VIDEODRIVER=x11
exec mangohud "$@"
