#!/bin/sh

readonly _name="file-browser"
readonly _image="docker.io/filebrowser/filebrowser"
readonly _tag="v2.24.1"

# Use podman, don't use docker
readonly _cmd="podman"

_prep_mounts() {
  readonly _mount1="${HOME}/.local/etc/containers/${_name}/data"
  readonly _mount2="${HOME}/.local/etc/containers/${_name}/config"

  mkdir -p "${_mount1}" || return 1
  mkdir -p "${_mount2}" || return 1

  # filebrowser needs these files to exist when mounted for the first time
  # mount path is defined in the default config.json
  touch "${_mount2}/database.db" || return 1

  _mounts=""
  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/srv"
  _mounts="${_mounts} --mount type=bind,source=${_mount2}/database.db,target=/database.db"

  readonly _mounts
  return 0
}

_prep_caps() {
  _caps=""

  # To mount the database "again" once it has been run more than once
  _caps="${_caps} --cap-add DAC_OVERRIDE"

  # Server runs on port 80
  _caps="${_caps} --cap-add NET_BIND_SERVICE"

  readonly _caps
  return 0
}

_prep_ports() {
  _ports=""

  # Bind to our Tailscale interface and ourselves
  for _ip in 127.0.0.1 100.122.254.80; do
    _ports="${_ports} -p ${_ip}:1337:80/tcp"
  done

  readonly _ports
  return 0
}

_check_user() {
  if [ "$(id -u)" -eq 0 ]; then
    printf -- 'You must run this as a rootless container\n'
    return 1
  fi

  _userns="--user=$(id -u):$(id -g) --userns keep-id"

  readonly _userns

  return 0
}

_check_health() {
  _health=""

  # systemd does not like spawning this healthcheck
  if [ "$(uname)" != "Darwin" ]; then
    _health="--health-cmd none"
  fi

  readonly _health

  return 0
}

_containerize() {
  # Log the commands we use next
  # Fail on errors
  # Fail on unassigned
  set -xeu

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  exec ${_cmd} run ${_how} \
    --name "${_name}" --hostname "${_name}" \
    --security-opt no-new-privileges:true --cap-drop ALL \
    ${_mounts} \
    ${_ports} \
    ${_caps} \
    ${_userns} \
    ${_health} \
    "${_image}:${_tag}" "$@"
}

main() {
  _check_user || return 1
  _check_health || return 1
  _prep_mounts || return 1
  _prep_ports || return 1
  _prep_caps || return 1

  # How do we run?
  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
    shift
    _how="-d --restart=unless-stopped"
  else
    _how="--rm -i -t"
  fi
  readonly _how

  _containerize "$@" || return 1
  return 0
}

main "$@" || exit 1
exit 0
