#!/bin/sh

readonly _name="cs2"

main() {
  # How do we run?
  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
    shift
    _how="$1"
  else
    _how=""
  fi
  readonly _how

  _target_dir="$(dirname "$0")"
  readonly _target_dir

  _cmd=""
  case "$1" in
    install)
      shift
      _cmd="+force_install_dir /data +login anonymous +app_update 730 validate +quit"
      ;;
    run)
      shift
      _cmd="+force_install_dir /data +login anonymous +app_update 730 validate +quit"
      ;;
    *)
      printf -- 'Unable to handle command: %s\n' "$1"
      printf -- 'Must be one of "install" "run"\n'
      return 1
      ;;
  esac
  readonly _cmd

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  exec "${_target_dir}/steamcmd" ${_how} "${_name}" ${_cmd} "$@"
}

main "$@" || exit 1
exit 0
