#!/bin/sh

# Splits up a user:path argument provided to a systemd instance unit
# and pass the expected format over to `tmpfs-mounter`

main() {
  _cmd="$1"
  _instance="$2"

  if [ -z "${_cmd}" ]; then
    printf -- 'Missing command, not forwarding to tmpfs-mounter.\n'

    unset _cmd
    unset _instance
    return 1
  fi

  if [ -z "${_instance}" ]; then
    printf -- 'Missing instance, not forwarding to tmpfs-mounter.\n'

    unset _cmd
    unset _instance
    return 1
  fi

  # Split the instance by colon
  _split="$(printf -- '%s' "${_instance}" | tr ':' ' ')"
  unset _instance

  # Grab the user and path (path is escaped by systemd)
  _user="$(printf -- '%s' "${_split}" | awk '{ print $1 }')"
  _path="$(printf -- '%s' "${_split}" | awk '{ print $2 }')"
  unset _split

  # Fix the path
  _unescaped_path="$(systemd-escape --unescape "${_path}")"
  unset _path

  # Pass to tmpfs-mounter
  exec /opt/pyamsoft/sbin/tmpfs-mounter "${_cmd}" "${_unescaped_path}" "${_user}"
}

main "$@" || exit 1
exit 0
