#!/bin/sh

# Clone the repo as bar into the dotfiles folder
git clone --bare "https://github.com/pyamsoft/dots" "${HOME}"/.dotfiles

# The dotfiles alias
alias dotfiles='git --git-dir "${HOME}"/.dotfiles --work-tree "${HOME}"'

# Configure the repository to only show explicitly added files
dotfiles config --local status.showUntrackedFiles no

printf -- 'When you are ready, run the following:\n\n'
printf -- '$ %s\n' "alias dotfiles='git --git-dir \"\${HOME}\"/.dotfiles --work-tree \"\${HOME}\"'"
printf -- '$ %s\n' "dotfiles checkout"
printf -- '\nSee "%s" for more information\n' "https://www.atlassian.com/git/tutorials/dotfiles"
