#!/bin/sh

if [ -z "$1" ]; then
  printf -- 'dots: Must provide "install", "uninstall", "test-install", or "test-uninstall".\n'
  exit 1
fi

if ! command -v 'stow' > /dev/null 2>&1; then
  printf -- 'GNU stow must be installed.\n'
  exit 2
fi

targets="automatic"

ensure_dirs()
{
    mkdir -p "${HOME}/.local/bin" || return 1
    mkdir -p "${HOME}/.local/share/flatpak" || return 1
    mkdir -p "${HOME}/.bww" || return 1
    mkdir -p "${HOME}/.config/lvim" || return 1
    return 0
}

print_postsetup_lvim()
{
    printf -- 'You may wish to install LunarVim:\n' || return 1
    printf -- '%s\n' 'bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)' || return 1
    return 0
}

print_postsetup()
{
  print_postsetup_lvim || return 1
  return 0
}

case "$1" in
  install)
    # Ensure some real directories are created in advance
    ensure_dirs || exit 1

    # shellcheck disable=SC2086
    stow -v -S ${targets} || exit 1

    print_postsetup_lvim || exit 1

    exit 0
    ;;
  uninstall)
    # shellcheck disable=SC2086
    stow -v -D ${targets} || exit 1
    exit 0
    ;;
  test-install)
    ensure_dirs || exit 1

    # shellcheck disable=SC2086
    stow -v -n -S ${targets} || exit 1

    print_postsetup_lvim || exit 1

    exit 0
    ;;
  test-uninstall)
    # shellcheck disable=SC2086
    stow -v -n -D ${targets} || exit 1
    exit 0
    ;;
  *)
    printf -- 'dots: Must provide "install", "uninstall", "test-install", or "test-uninstall".\n'
    exit 1
    ;;
esac
