#!/bin/sh

_path=""
if [ "$1" = "media" ]; then
  _path="nerd@nerd2:/home/nerd/media/holding"
  shift
else
  _path="nerd@nerd2:/home/nerd/holding"
fi
readonly _path

for f in "$@"; do
  # Remove a trailing space to copy over folders
  _file="${f%/}"
  if command -v sshpass >/dev/null; then
    sshpass -f "${HOME}/.nerd2-passwd" rsync -hrtplu --progress "${_file}" "${_path}"
  else
    rsync -hrtplu --progress "${_file}" "${_path}"
  fi
done

