#!/bin/sh

_enter_jail() {
  _jail_user="$1"

  jail --name "free-games-${_jail_user}" bash -c './claimer' || return 1

  unset _jail_user
  return 0
}

_install_script() {
  _jail_owner="$1"

  if [ -z "${_jail_owner}" ]; then
    printf -- 'Cannot install claimer script without jail owner.\n'

    unset _jail_owner
    return 1
  fi

  _jail_home="${HOME}/.local/etc/jails/free-games-${_jail_owner}"
  mkdir -p "${_jail_home}" || {
    printf -- 'Unable to create jail home directory: %s' "${_jail_home}"

    unset _jail_owner
    unset _jail_home
    return 1
  }

  printf -- 'Install game claimer script into %s\n' "${_jail_home}"

  # Install script
  cat <<EOF >"${_jail_home}/claimer"
#!/bin/sh

if [ ! -d "free-games-claimer" ]; then
  printf -- 'Install free-games-claimer from github...\n'
  git clone 'https://github.com/vogler/free-games-claimer' || {
    printf -- 'Failed to clone free-games-claimer repository.\n'
    exit 1
  }
fi

printf -- 'Enter free-games-claimer directory...\n'
cd free-games-claimer || {
  printf -- 'Failed to enter free-games-claimer repository.\n'
  exit 1
}

printf -- 'Update repository to latest...\n'
git pull || {
  printf -- 'Failed to pull free-games-claimer repository.\n'
  exit 1
}

printf -- 'Install dependencies...\n'
npm install || {
  printf -- 'Failed to install nodejs dependencies.\n'
  exit 1
}

pipx install apprise || {
  printf -- 'Failed to install python dependencies.\n'
  exit 1
}

# Run the VNC on a different X
export DISPLAY="${DISPLAY}"

# free-games-claimer options 
export NOTIFY="${NOTIFY}"
export SHOW="${SHOW}"

printf -- 'Claim from Epic Games...\n'
node epic-games.js || {
  printf -- 'Failed to claim from Epic Games.\n'
}

printf -- 'Claim from Prime Gaming...\n'
node prime-gaming.js || {
  printf -- 'Failed to claim from Prime Gaming.\n'
}

printf -- 'Claim from GOG...\n'
node gog.js || {
  printf -- 'Failed to claim from GOG.\n'
}

exit 0
EOF

  # Mark exec
  chmod 700 "${_jail_home}/claimer"

  unset _jail_owner
  unset _jail_home
  return 0
}


main() {
  _user="$1"

  if [ -z "${_user}" ]; then
    printf -- 'Must provide target user to claim free games.\n'

    unset _user
    return 1
  fi

  _install_script "${_user}" || return 1
  _enter_jail "${_user}" || return 1

  unset _user
  return 0
}

main "$@" || exit 1
exit 0
