#!/bin/sh

_dconf_write() {
  _dconf_key="$1"
  _dconf_value="$2"

  dconf write "${_dconf_key}" "${_dconf_value}" || {
    printf -- 'Failed writing %s to DCONF %s\n' "${_dconf_value}" "${_dconf_key}"
    unset _dconf_key
    unset _dconf_value
    return 1
  }

  unset _dconf_key
  unset _dconf_value
  return 0
}

main() {
  case "$1" in
  l | light)
    _dconf_write "/org/guake/style/font/palette" "'#5c5c5f5f7777:#d2d20f0e3939:#4040a0a02b2b:#dfdf8e8e1d1d:#1e1e6665f5f5:#eaea7675cbca:#171792929999:#acacb0b0bebe:#6f6e6f6e8585:#d2d20f0e3939:#4040a0a02b2b:#dfdf8e8e1d1d:#1e1e6665f5f5:#eaea7675cbca:#171792929999:#bcbcc0c0cccc:#4c4c4f4e6969:#efeff1f1f5f5'"
    ;;
  d | dark)
    _dconf_write "/org/guake/style/font/palette" "'#49494d4d6464:#eded87869696:#a6a5dada9595:#eeeed4d49f9f:#8a8aadadf4f4:#f5f5bdbde6e6:#8b8bd5d5caca:#b8b8c0c0e0e0:#5b5a605f7878:#eded87869696:#a6a5dada9595:#eeeed4d49f9f:#8a8aadadf4f4:#f5f5bdbde6e6:#8b8bd5d5caca:#a5a5adadcbcb:#cacad3d3f5f5:#242427273a3a'"
    ;;
  *)
    printf -- 'Must be one of "light" "dark"\n'
    return 1
    ;;
  esac

  return 0
}

main "$@" || exit 1
exit 0
