#!/bin/bash

# shellcheck disable=SC1090
[ -f "${HOME}"/.xprofile ] && . "${HOME}"/.xprofile

# These must be unset to have dbus launch
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1

exec startxfce4
