#!/bin/sh

# shellcheck disable=SC1090
[ -f "${HOME}"/.xprofile ] && . "${HOME}"/.xprofile

# These must be unset to have dbus launch
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Do not attempt hardware rendering since we don't have hardware access
export LIBGL_ALWAYS_SOFTWARE=1


exec startxfce4
