#!/bin/sh

# S3TC texture filtering
export force_s3tc_enable=true

# Fix artifacting on AMDGPU (https://github.com/Plagman/gamescope/issues/320)
export AMD_DEBUG=nodcc
export RADV_DEBUG=nodcc

# Fix distortion on Intel (https://github.com/Plagman/gamescope/issues/356)
export INTEL_DEBUG=norbc

# Ignore forced TearFree display sync
export vblank_mode=0

# Run the executable in a session
# printf -- 'Running gametime: %s %s\n' "gamescope -w 1366 -h 768  -U -W 1600 -H 900 -e -b -r 120 -o 60 --rt" "$*"
# exec gamescope -w 1366 -h 768  -U -W 1600 -H 900 -e -b -r 120 -o 60 --rt -- "$@"

# Raw execute, no gamescope (crashes with std::pthread not allowed error)
exec "$@"
