#!/bin/sh

# For gamescope, the following is needed
# --devices=all;shm; is needed for Steam overlay and Steam input
# --env SDL_VIDEODRIVER=x11 must be set on the flatpak itself, not just in this file.

# S3TC texture filtering
export force_s3tc_enable=true

# Fix artifacting on AMDGPU (https://github.com/Plagman/gamescope/issues/320)
export AMD_DEBUG=nodcc
export RADV_DEBUG=nodcc

# Fix distortion on Intel (https://github.com/Plagman/gamescope/issues/356)
export INTEL_DEBUG=norbc

# Ignore forced TearFree display sync
export vblank_mode=0

# Run the executable in a session
# NOTE: Shouldn't crash if the environment sets SDL_VIDEODRIVER=x11
exec gamescope \
  -w 1280 -h 720 \
  -W 1920 -H 1080 \
  -r 120 -o 60 \
  -e \
  -b \
  -U --fsr-sharpness 10 \
  -- "$@"
