#!/bin/sh

readonly _name="adguardhome"
readonly _image="docker.io/adguard/adguardhome"
readonly _tag="v0.107.43"

# Use podman, don't use docker
readonly _cmd="podman"

_runas() {
  sudo -u "${_user}" -- "$@" || return 1
  return 0
}

_get_env() {
  _runas env | grep "^${1}=" | tr '=' ' ' | awk '{ print $2 }' || return 1

  unset _env_user
  return 0
}

_priv_port_drop() {
  if [ "$(uname)" != "Darwin" ]; then
    # Open privileged ports for non-root users
    # After a few seconds, close them back up.
    #
    # Since we run this overall script as root, we are "trusted" to open this
    sysctl -q net.ipv4.ip_unprivileged_port_start=53 || return 1
    (sleep 3 && sysctl -q net.ipv4.ip_unprivileged_port_start=1024) &
    return 0
  fi

  return 0
}

_prep_mounts() {
  _root_path="$(_get_env "HOME")/.local"
  readonly _root_path

  readonly _mount1="${_root_path}/etc/containers/${_name}/conf"

  # Prep the directories
  _runas mkdir -m 700 -p "${_mount1}" || return 1

  _mounts=""
  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/opt/adguardhome/conf"

  # For some reason, this path cannot be bound on MacOS
  # Complains like:
  #
  # -> [error] auth: open DB: /opt/adguardhome/work/data/sessions.db: invalid argument
  # -> [error] AdGuard Home cannot be initialized due to an incompatible file system.
  if [ "$(uname)" != "Darwin" ]; then
    readonly _mount2="${_root_path}/etc/containers/${_name}/work"
    _runas mkdir -m 700 -p "${_mount2}" || return 1
    _mounts="${_mounts} --mount type=bind,source=${_mount2},target=/opt/adguardhome/work"
  fi

  readonly _mounts
  return 0
}

_prep_caps() {
  _caps=""
  _caps="${_caps} --cap-add NET_BIND_SERVICE"

  # Need these extra caps on MacOS
  if [ "$(uname)" = "Darwin" ]; then
    _caps="${_caps} --cap-add DAC_OVERRIDE"
    _caps="${_caps} --cap-add FOWNER"
  fi

  readonly _caps
  return 0
}

_prep_ports() {
  _ports=""

  # MacOS doesn't like us binding to localhost only priv ports, use the general syntax and it
  # does not complain for some rason
  if [ "$(uname)" = "Darwin" ]; then
    # DNS
    _ports="${_ports} -p 53:53/tcp"
    _ports="${_ports} -p 53:53/udp"

    # Admin Console
    _ports="${_ports} -p 2081:81/tcp"
  else
    # DNS
    _ports="${_ports} -p 127.0.0.1:53:53/tcp"
    _ports="${_ports} -p 127.0.0.1:53:53/udp"

    # Admin Console
    _ports="${_ports} -p 127.0.0.1:2081:81/tcp"
  fi

  readonly _ports
  return 0
}

_check_user() {
  # On MacOS we use a VM, make sure it is rootful to bind to port 53
  if [ "$(uname)" = "Darwin" ]; then
    if [ "$(id -u)" -eq 0 ]; then
      printf -- 'You must run this as a normal user with a rootful VM\n'
      return 1
    fi
  else
    if [ "$(id -u)" -ne 0 ]; then
      printf -- 'You must run this as a rootful container\n'
      return 1
    fi
  fi

  _userns=""
  # No user namespace
  readonly _userns

  return 0
}

_containerize() {
  # Runtime configuration
  _ah=""

  # Optional runtime config (so we don't have to hardcode keys)
  _runconf="$(_get_env "HOME")/.local/etc/containers/${_name}/runconfig.env"
  if [ -e "${_runconf}" ]; then
    # Source the file into the environment
    # shellcheck disable=SC1090
    . "${_runconf}" || return 1
  else
    printf -- 'Optional runconfig.env supported at "%s"\n' "${_runconf}"
  fi
  unset _runconf
  readonly _ah

  # Only compare the version minors, since bc only can do floating point, not semver :(
  _is_cmd_new_enough="$(printf -- '%s >= 4.7' "$(podman --version | awk '{ print $3 }' | tr '.' ' ' | awk '{ print $1 "." $2}')" | bc)"

  # We use our container DNS resolver
  # MacOS can't launch with host-gateway
  _network="--add-host localhost:127.0.0.1 --dns 127.0.0.1 --dns-search=."
  if [ "$(uname)" = "Linux" ] && [ 1 -eq "${_is_cmd_new_enough}" ]; then
    _network="${_network} --add-host host.containers.internal:host-gateway"
  fi
  readonly _network

  unset _is_cmd_new_enough

  # Open ports to non-root users
  _priv_port_drop || return 1

  # Log the commands we use next
  # Fail on errors
  # Fail on unassigned
  set -xeu

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  _runas ${_cmd} run ${_how} \
    --name "${_name}" --hostname "${_name}" \
    --security-opt no-new-privileges:true --cap-drop ALL \
    ${_network} \
    ${_mounts} \
    ${_ports} \
    ${_caps} \
    ${_userns} \
    "${_image}:${_tag}" "$@"
}

main() {
  if [ -z "$1" ]; then
    printf -- 'Must provide target runas user\n'
    return 1
  fi

  # Make sure the target user is provided
  _user="$(id -un "$1")"
  readonly _user

  if [ -z "${_user}" ]; then
    printf -- 'Must provide target runas user\n'
    return 1
  fi

  # Consume the used var
  shift

  # Check that we are not targeting root
  if [ "$(id -u "${_user}")" -eq 0 ]; then
    printf -- 'Your target user must not be root: %s\n' "${_user}"
    return 1
  fi

  _check_user || return 1
  _prep_mounts || return 1
  _prep_ports || return 1
  _prep_caps || return 1

  # How do we run?
  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
    shift
    _how="-d --restart=unless-stopped"
  else
    _how="--rm -i -t"
  fi

  readonly _how

  _containerize "$@" || return 1
  return 0
}

main "$@" || exit 1
exit 0
