#!/bin/sh

main() {
  _name="$1"

  if [ -z "${_name}" ]; then
    printf -- 'Must provide container name to teardown\n.'
    return 1
  fi

  # Attempt nice stop
  printf -- 'Attempt nice stop container: %s\n' "${_name}"
  podman stop -t 5 "${_name}" >/dev/null || {
    printf -- 'Failed to nicely stop container %s\n' "${_name}"
  }

  # Remove the container
  printf -- '\nAttempt force-remove container: %s\n' "${_name}"
  podman rm -f "${_name}" >/dev/null || {
    printf -- 'Failed to force remove the container %s\n' "${_name}"
    return 1
  }

  # Remove the network
  printf -- '\nAttempt remove container network: %s\n' "${_name}"
  podman network rm "${_name}" >/dev/null || {
    printf -- 'Failed to remove the container network: %s\n' "${_name}"
  }

  printf -- '\nContainer is completely torn down: %s\n' "${_name}"
  return 0
}

main "$@" || exit 1
exit 0
