#!/bin/sh

_target_user="$(basename "$0")"
readonly _target_user

_check_user() {
  if ! id -u "${_target_user}" >/dev/null 2>&1; then
    printf -- 'Target user %s does not exist!\n' "${_target_user}"
    return 1
  fi

  return 0
}

main() {
  if ! _check_user; then
    return 1
  fi

  exec sudo -u "${_target_user}" /opt/pyamsoft/bin/delegate-containers "$@"
  return 0
}

main "$@" || exit 1
exit 0
