#!/bin/sh

# Execute a shell as a containers-* user, even if the user's shell is
# set as /bin/nologin

_runas() {
  if command -v run0 >/dev/null 2>&1; then
    # Use run0 if we have it
    exec sudo run0 -u "$1" --setenv=SHELL=/bin/bash
  else
    # Otherwise fake the environment with sudo
    exec sudo -u "$1" env SHELL=/bin/bash XDG_RUNTIME_DIR="/run/user/$(id -u "$1")" /bin/bash -l
  fi
}

main() {
  _user="containers-$1"
  if ! id -un "${_user}" >/dev/null 2>&1; then
    printf -- 'Target user %s does not exist\n' "${_user}"
    return 1
  fi

  _runas "${_user}" || return 1

  unset _user

  return 0
}

main "$@" || exit 1
exit 0
