#!/bin/sh

_USER=""

# Crashes right after with some QT session error
readonly _LAUNCH_FW_APPLET=0

_x_setup() {
  # Setup xhost for localhost
  if command -v xhost >/dev/null 2>&1; then
    # Do not run in background, this must be complete before continuing
    xhost "+si:localuser:${_USER}"
  fi

  # Disable the terminal bell noise
  # Set keyboard repeat rate to 300[60]
  if command -v xset >/dev/null 2>&1; then
    # Do not run in background, this must be complete before continuing
    xset -b r rate 300 60
  fi

  return 0
}

_startup_programs() {
  # Sunshine
  # The systemd user service is broken so we manually launch this way for now
  if command -v restart-sunshine >/dev/null 2>&1; then
    restart-sunshine
  fi

  # Corectrl
  if command -v corectrl >/dev/null 2>&1; then
    corectrl >/dev/null 2>&1 &
  fi

  # If we have firewall applet
  if [ "${_LAUNCH_FW_APPLET}" -ne 0 ]; then
    if command -v firewall-applet >/dev/null 2>&1; then
      # Wait a little bit (sometimes it crashes)
      sleep 5

      # And its not currently running
      if pgrep -u "${_USER}" firewall-applet >/dev/null; then
        # Start a new one
        firewall-applet >/dev/null 2>&1 &
      fi
    fi
  fi

  return 0
}

main() {
  _USER="$(id -un)"

  # Source the environment
  # shellcheck disable=SC1091
  [ -f "${HOME}/.environment" ] && . "${HOME}/.environment"

  if [ "${XDG_SESSION_TYPE}" = "x11" ]; then
    # Setup X11 generic
    _x_setup || {

      unset _USER
      return 1
    }
  fi

  # Then execute startup programs
  _startup_programs || {

    unset _USER
    return 1
  }

  unset _USER
  return 0
}

main "$@"
