#!/bin/sh

_x_setup() {
  # Setup xhost for localhost
  if command -v xhost >/dev/null 2>&1; then
    # Do not run in background, this must be complete before continuing
    xhost "+si:localuser:$(id -un)"
  fi

  # Clean source xrdb config
  _xrdb_path="${XDG_CONFIG_HOME:-${HOME}/.config}/Linux/resources"
  if command -v xrdb >/dev/null 2>&1 && [ -f "${_xrdb_path}" ]; then
    # Do not run in background, this must be complete before continuing
    xrdb "${_xrdb_path}"
  fi
  unset _xrdb_path

  # Disable the terminal bell noise
  # Set keyboard repeat rate to 300[60]
  if command -v xset >/dev/null 2>&1; then
    # Do not run in background, this must be complete before continuing
    xset -b r rate 300 60
  fi

  return 0
}

_startup_programs() {
  # Sunshine
  # The systemd user service is broken so we manually launch this way for now
  if command -v restart-sunshine >/dev/null 2>&1; then
    restart-sunshine
  fi

  return 0
}

main() {
  if [ "${XDG_SESSION_TYPE}" = "x11" ]; then
    # Setup X11 generic
    _x_setup || return 1
  fi

  # Then execute startup programs
  _startup_programs || return 1

  return 0
}

main "$@"
