#!/bin/sh

# Copy real themes over to flatpak friendly locations

_do_theme() {
  _theme="$1"

  _t="/usr/share/themes/${_theme}"
  if [ -z "$1" ] || [ ! -d "${_t}" ]; then
    printf -- 'Sorry, theme %s does not exist on host!\n' "${_t}"
    unset _t
    unset _theme
    return 1
  fi

  # Copy theme
  mkdir -p "${HOME}/.themes"
  cp -r "${_t}" "${HOME}/.themes"
  if [ "${_dark}" -eq 1 ]; then
    _t="/usr/share/themes/${_theme}-Dark"
    if [ -d "${_t}" ]; then
      cp -r "${_t}" "${HOME}/.themes"
    fi

    _t="/usr/share/themes/${_theme}-dark"
    if [ -d "${_t}" ]; then
      cp -r "${_t}" "${HOME}/.themes"
    fi

    _t="/usr/share/themes/${_theme}_Dark"
    if [ -d "${_t}" ]; then
      cp -r "${_t}" "${HOME}/.themes"
    fi

    _t="/usr/share/themes/${_theme}_dark"
    if [ -d "${_t}" ]; then
      cp -r "${_t}" "${HOME}/.themes"
    fi
  fi

  unset _t
  unset _theme
  return 0
}

_do_icon() {
  _icon="$1"

  _i="/usr/share/icons/${_icon}"
  if [ -z "$1" ] || [ ! -d "${_i}" ]; then
    printf -- 'Sorry, icon %s does not exist on host!\n' "${_i}"
    unset _icon
    unset _i
    return 1
  fi

  # Copy theme
  mkdir -p "${HOME}/.icons"
  cp -r "${_i}" "${HOME}/.icons"
  if [ "${_dark}" -eq 1 ]; then
    _i="/usr/share/icons/${_icon}-Dark"
    if [ -d "${_i}" ]; then
      cp -r "${_i}" "${HOME}/.icons"
    fi

    _i="/usr/share/icons/${_icon}-dark"
    if [ -d "${_i}" ]; then
      cp -r "${_i}" "${HOME}/.icons"
    fi

    _i="/usr/share/icons/${_icon}_Dark"
    if [ -d "${_i}" ]; then
      cp -r "${_i}" "${HOME}/.icons"
    fi

    _i="/usr/share/icons/${_theme}_dark"
    if [ -d "${_i}" ]; then
      cp -r "${_i}" "${HOME}/.icons"
    fi
  fi

  unset _i
  unset _icon
  return 0
}

main() {
  _dark=0
  if [ -n "$1" ] && [ "$1" = "--dark" ]; then
    _dark=1
    shift
  fi

  _do_theme "$1" || return 1
  shift
  _do_icon "$1" || return 1

  return 0
}

main "$@" || exit 1
exit 0
