#!/bin/sh

##
# Installer
#
# $1 flatpak app name
# $2 script to install from this directory
_installer() {
  app_name="$1"
  target="$2"
  script="$3"
  mark="$4"
  current_directory="$(pwd)"

  printf -- 'Attempt install script %s into flatpak app %s\n' "${script}" "${app_name}"

  if [ -d "${HOME}/.var/app/${app_name}" ]; then
    cd "${HOME}/.var/app/${app_name}" || {
      printf -- 'Failed to cd into flatpak app directory: %s\n.' "${app_name}"
      return 1
    }

    mkdir -p "${target}" || {
      printf -- 'Failed to create %s directory for app: %s\n' "${target}" "${app_name}"
      return 2
    }

    t="${target}/$(basename "${script}")"

    cp -f "${current_directory}/${script}" "$t" || {
      printf -- 'Failed to copy script %s into %s directory for app: %s\n' "${script}" "${target}" "${app_name}"
      return 3
    }

    if [ "${mark}" -eq 1 ]; then
      chmod +x "$t" || {
        printf -- 'Failed to mark script %s executable for app: %s\n' "${script}" "${app_name}"
        return 4
      }
    else
      chmod -x "$t" || {
        printf -- 'Failed to mark script %s unexecutable for app: %s\n' "${script}" "${app_name}"
        return 4
      }
    fi

    cd "${current_directory}" || {
      printf -- 'Failed to cd out of flatpak app directory: %s back to %s\n.' "${app_name}" "${current_directory}"
      return 5
    }

    printf -- '    %s installed for flatpak app %s\n' "${script}" "${app_name}"

    unset t
    unset app_name
    unset target
    unset script
    unset mark
    unset current_directory
  fi

  return 0
}

_local_install() {
  script="$1"
  current_directory="$(pwd)"

  printf -- 'Attempt local install script %s into host\n' "${script}"

  t="${HOME}/.local/bin/$(basename "${script}")"

  cp -f "${current_directory}/${script}" "$t" || {
    printf -- 'Failed to copy script %s into host\n' "${script}"
    return 1
  }

  chmod 700 "$t" || {
    printf -- 'Failed to mark script %s executable for host\n' "${script}"
    return 2
  }

  printf -- '    %s installed for host\n' "${script}"

  unset t
  unset script
  unset current_directory
  return 0
}

_installer "com.heroicgameslauncher.hgl" ".local/bin" "gametime" 1 || exit 1
_installer "com.valvesoftware.Steam" ".local/bin" "gametime" 1 || exit 1
_installer "io.openrct2.OpenRCT2" ".local/bin" "gametime" 1 || exit 1
_installer "com.moonlight_stream.Moonlight" ".local/bin" "gametime" 1 || exit 1

_installer "com.heroicgameslauncher.hgl" "config/vkBasalt" "vkBasalt.conf" 0 || exit 1
_installer "com.valvesoftware.Steam" "config/vkBasalt" "vkBasalt.conf" 0 || exit 1
_installer "io.openrct2.OpenRCT2" "config/vkBasalt" "vkBasalt.conf" 0 || exit 1

_installer "io.openrct2.OpenRCT2" ".local/bin" "openrct2/gametime-openrct2" 1 || exit 1
_installer "com.moonlight_stream.Moonlight" ".local/bin" "moonlight/gametime-moonlight" 1 || exit 1

_local_install "gametime" || exit 1

exit 0
