#!/bin/sh

_restart_unbound_container() {
  if [ -z "${CONNECTIVITY_STATE}" ] || [ "${CONNECTIVITY_STATE}" != "FULL" ]; then
    printf -- 'No Internet access, stop Unbound DNS container.\n'
    run0 -u containers-network -i -- systemctl --user stop container@unbound.service || {
      printf -- 'Failed to stop Unbound container.\n'
      return 1
    }
    return 0
  fi

  printf -- 'Network connection changed, restart Unbound DNS container.\n'
  run0 -u containers-network -i -- systemctl --user restart container@unbound.service || {
    printf -- 'Failed to restart Unbound container.\n'
    return 1
  }
  return 0
}

main() {
  case "$2" in
  connectivity-change)
    _restart_unbound_container "$@" || return 1
    ;;
  esac

  return 0
}

main "$@" || exit 1
exit 0
