#!/bin/sh

if [ "$(id -u)" -eq 0 ]; then
  printf -- 'Do not run as root\n'
  exit 1
fi

# Do not exec here since bww will exec for you
# Need absolute path to bww script to jail
# Indicator kdeconnect must see that kdeconnectd is running
#
# Force name for cleaner folder
# Bind shared downloads folder
# Need access to systemd for systemctl suspend
# Need access to pid namespace to avoid polkit warning message on systemctl command
# NOTE: systemctl command will still work... even if warning were to show.
"${HOME}/.local/bin/bww" \
  --private \
  --forcename="kdeconnectd" \
  --bind-if-exists "${HOME}/downloads" \
  --bind-if-exists "${HOME}/.config/kdeconnect" \
  --systemd --nopid \
  /usr/lib/kdeconnectd-real "$@"
