#!/usr/bin/env bash

# Build the bash environment
_exports=""
_exports="${_exports} LUNARVIM_RUNTIME_DIR=${LUNARVIM_RUNTIME_DIR:-/Users/peter/.local/share/lunarvim}"
_exports="${_exports} LUNARVIM_CONFIG_DIR=${LUNARVIM_CONFIG_DIR:-/Users/peter/.config/lvim}"
_exports="${_exports} LUNARVIM_CACHE_DIR=${LUNARVIM_CACHE_DIR:-/Users/peter/.cache/lvim}"
_exports="${_exports} LUNARVIM_BASE_DIR=${LUNARVIM_BASE_DIR:-/Users/peter/.local/share/lunarvim/lvim}"

_cmd="export ${_exports}; exec -a lvim nvim -u ${LUNARVIM_BASE_DIR:-/Users/peter/.local/share/lunarvim/lvim}/init.lua $*"

# We run the AS shell to provide Java support
android-studio --shell -c "${_cmd}"
