# https://www.kernel.org/doc/Documentation/sysctl/kernel.txt

# Restrict kernel pointers and dmesg access
kernel.dmesg_restrict = 1

# Yama hardening
kernel.yama.ptrace_scope = 1

# Work around for a BPF root exploit
kernel.unprivileged_bpf_disabled = 1

# Memory protection
kernel.randomize_va_space = 2

