#!/bin/sh
# X11 environment

# Sleep for a little bit before we get started
sleep 5

# Setup xhost for localhost
if command -v whoami > /dev/null 2>&1 && command -v xhost > /dev/null 2>&1; then
  xhost "+si:localuser:$(whoami)" &
fi

# Clean source xrdb config
xrdb_path="${XDG_CONFIG_HOME:-${HOME}/.config}/resources"
if command -v xrdb > /dev/null 2>&1 && [ -f "${xrdb_path}" ]; then
  xrdb "${xrdb_path}" &
fi
unset xrdb_path

# Disable the terminal bell noise
if command -v xset > /dev/null 2>&1; then
  xset -b &
fi

# XBindkeys
if command -v xbindkeys > /dev/null 2>&1; then
  xbindkeys &
fi

# CoreCtrl
if command -v corectrl > /dev/null 2>&1; then
  corectrl &
fi

# EasyEffects
if command -v com.github.wwmm.easyeffects > /dev/null 2>&1; then
  com.github.wwmm.easyeffects --gapplication-service &
fi

# Sunshine
# The systemd user service is broken so we manually launch this way for now
if command -v sunshine > /dev/null 2>&1; then
  sunshine &
fi
