#!/bin/sh

_devel="${HOME}/devel"
_sdk="${_devel}/sdk/android"

_shell=""
if [ -n "$1" ] && [ "$1" = "--shell" ]; then
  _shell="--shell"
  shift
fi

# Generally speaking, you aren't building by hand on the command line so you
# won't need this on the PATH
# PATH="${_sdk}/build-tools/35.0.0:${PATH}"
PATH="${_sdk}/cmdline-tools/latest:${PATH}"
PATH="${_sdk}/platform-tools:${PATH}"
export PATH

export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export JAVA_HOME="/opt/android-studio/jbr"

exec jail ${_shell} "$(basename "$0")" \
  --bind "${_sdk}" "${_sdk}" \
  --bind "${_devel}/project/pyamsoft/android" "${_devel}/project/pyamsoft/android" \
  --setenv JAVA_HOME "${JAVA_HOME}" \
  --setenv ANDROID_EMULATOR_USE_SYSTEM_LIBS "${ANDROID_EMULATOR_USE_SYSTEM_LIBS}" \
  --setenv PATH "${PATH}" \
  -- \
  "$@"

