#!/bin/sh

# Heroic with games

exec jail "$(basename "$0")" \
  --new-session \
  --bind "${HOME}/games/heroic" "${HOME}/games/heroic" \
  --bind "${HOME}/.local/bin/gametime" "${HOME}/.local/bin/gametime" \
  -- \
  "$@"
