#!/bin/sh

# Steam with games

exec jail "$(basename "$0")" \
  --new-session \
  --bind "${HOME}/games/steam" "${HOME}/games/steam" \
  --bind "${HOME}/.local/bin/gametime" "${HOME}/.local/bin/gametime" \
  -- \
  "$@"
