#!/bin/sh

readonly dev_root="${HOME}/devel"
readonly project_root="${dev_root}/project/pyamsoft/js"

# Local scripts
path="${HOME}/.local/bin"

readonly path

# Even if you run with Wayland
# https://wiki.archlinux.org/title/Android#Android_Studio
#
# The launcher splash still uses XKB and X11, so you NEED this
# X11 flag here, even though after the launcher the actual program
# does NOT run in X11
#
# You can check xlsclients to be sure
jail --name webstorm --x11 -- /usr/bin/webstorm \
  --setenv PATH "${path}:${PATH}" \
  --setenv JAVA_HOME "/opt/webstorm/jbr/" \
  --bind "${project_root}" "${project_root}" \
  -- "$@"

exit 0
