#!/bin/sh

# For gamescope, the following is needed
# --devices=all;shm; is needed for Steam overlay and Steam input
# --env SDL_VIDEODRIVER=x11 must be set on the flatpak itself, not just in this file.
# You must use Proton-GE from within a flatpak, since Steam pressure-vessel messes up gamescope
# You must use Super+U to enable FSR in game

# S3TC texture filtering
export force_s3tc_enable=true

# Ignore forced TearFree display sync
export vblank_mode=0

# Fix weird texture bugs
# https://github.com/Plagman/gamescope/issues/320
export AMD_DEBUG=nodcc
export RADV_DEBUG=nodcc

# Game workarounds
#
# Vampire survivors needs to run with logs on Proton Experimental or it crashes with a Javascript Error
# https://steamcommunity.com/app/1675200/discussions/1/3273566073555640279/
if printf -- '%s' "$*" | grep -q "$(cat << EOF
Vampire Survivors
EOF
)"; then
  export PROTON_LOGS=1
fi

# gamescope
# https://github.com/Plagman/gamescope
#
# Run games in Fullscreen at the nested resolution (which should be shown as the only FS res)
# FSR is between 0 (max) and 20 (min) instead of 0-5. Default is 2 => 8
#
# NOTE: Shouldn't crash if the environment sets SDL_VIDEODRIVER=x11
#
# NOTE: If we only provide a height, gamescope will assume the width as 16x9
#
# NOTE: ReadyOrNot has a minimum of 1368x768, change the config file and do not touch settings to have it be lower
#       If you open the settings in game, your FPS will go to 2.
#
# NOTE: Slay the Spire won't launch in Fullscreen if the resolution is below 1280x720, use Windowed mode
#
# NOTE: FSR performance is 2.0x nested resolution.
# NOTE: FSR balanced is 1.7x nested resolution.
# NOTE: FSR quality is 1.5x nested resolution.
#
# NOTE: Do not apply any FSR sharpness with gamescope, we will use vkBasalt for that
# NOTE: Shell math doesn't like decimals, so divide stuff by 10 instead
readonly target_width="1920"
readonly target_height="1080"
readonly fsr_level="15"
readonly window_type="--borderless"

# Options passed to gamescope session
gamescope_options="--output-height ${target_width} --output-height ${target_height} \
--nested-width $((target_width * 10 / fsr_level)) --nested-height $((target_height * 10 / fsr_level)) \
--fsr-upscaling --fsr-sharpness 20 \
--nested-refresh 75 --nested-unfocused-refresh 30 ${window_type}"

# vkBasalt
# https://github.com/DadSchoorse/vkBasalt
#
# Use with vkBasalt.conf to enable better CAS in games (gamescope has sharpening but it kinda sux)

# The game environment
# gamescope must call these tools directly instead of setting them in the outside environment
game_environment="ENABLE_VKBASALT=1"

# Extra tools to run as a wrapper
game_tools="mangohud"

# Default arguments passed to games
# These are common values that attempt to disable startup splash screens
game_arguments="-novid -nosplash -nostartupmovies"

# Mangohud
# https://github.com/flightlessmango/MangoHud#hud-configuration
#
# We cannot export MANGOHUD=1 before gamescope as it will crash or not report correctly.
# We must use gamescope to run mangohud, and then use mangohud to run our command.
export MANGOHUD_CONFIG=fps,cpu_temp,gpu_temp,ram,vram,fps_limit=75,gl_vsync=0,vsync=1,resolution,show_fps_limit,vkbasalt,gamemode,font_size=16,no_display

# OBS VKCapture
# https://github.com/nowrep/obs-vkcapture
#
# Depending on steam vs others, we set te OBS_VKCAPTURE at a different scope

# If we are running in steam, add --steam option, otherwise do not (causes weird window issues)
if [ "${FLATPAK_ID}" = "com.valvesoftware.Steam" ]; then
  gamescope_options="${gamescope_options} --steam"
  game_environment="${game_environment} OBS_VKCAPTURE=1"
elif [ "${FLATPAK_ID}" = "com.heroicgameslauncher.hgl" ]; then
  # For not Steam, we export this var here instead of within gamescope session
  export OBS_VKCAPTURE=1
fi

# shellcheck disable=SC2086
exec gamescope ${gamescope_options} -- env ${game_environment} ${game_tools} "$@" ${game_arguments}
