#!/bin/sh

# Variables
__hostname=""
__gamescope_options=""
__game_environment=""
__game_tools=""
__env_tools=""

##
# Get the hostname
_get_hostname()
{
  if [ -n "${HOSTNAME}" ]; then
    __hostname="${HOSTNAME}"
  elif command -v hostnamectl > /dev/null; then
    __hostname="$(hostnamectl hostname)"
  elif command -v hostname > /dev/null; then
    __hostname="$(hostname)"
  else
    __hostname=""
    return 1
  fi

  return 0
}

_export_gaming_environment()
{
  # Fix weird texture bugs
  # https://github.com/Plagman/gamescope/issues/320
  export AMD_DEBUG=nodcc
  export RADV_DEBUG=nodcc

  # May fix VKD3D issues
  # https://www.reddit.com/r/linux_gaming/comments/119hwmt/this_setting_may_help_vkd3d_games_that_have/
  export VKD3D_CONFIG=no_upload_hvv

  # Use single-file shader cache
  # https://www.phoronix.com/news/Mesa-Single-File-Cache
  export MESA_DISK_CACHE_SINGLE_FILE=1

  # Zink driver for OpenGL-over-Vulkan
  if [ -n "${GAME_ZINK}" ] && [ "${GAME_ZINK}" -ne 0 ]; then
    unset GAME_ZINK

    # Enable Zink driver
    # https://wiki.archlinux.org/title/OpenGL
    export __GLX_VENDOR_LIBRARY_NAME=mesa
    export MESA_LOADER_DRIVER_OVERRIDE=zink
    export GALLIUM_DRIVER=zink

    # Speed up
    # https://www.phoronix.com/news/Mesa-Zink-DB-Descriptor-Mode
    export ZINK_DESCRIPTOR_MODE=db

    # Load Vulkan layers to be compatible with stuff like vkbasalt
    # https://github.com/DadSchoorse/vkBasalt/issues/168
    export VK_INSTANCE_LAYERS="VK_LAYER_MANGOHUD_overlay;VK_LAYER_OBS_vkcapture_32;VK_LAYER_OBS_vkcapture_64;VK_LAYER_VKBASALT_post_processing"
    export VK_LAYER_PATH="/usr/lib/extensions/vulkan/share/vulkan/implicit_layer.d"
  fi

  return 0
}

##
# For gamescope, the following is needed
# --devices=all;shm; is needed for Steam overlay and Steam input
# --env SDL_VIDEODRIVER=x11 must be set on the flatpak itself, not just in this file.
# You must use Proton-GE from within a flatpak, since Steam pressure-vessel messes up gamescope
# You must use Super+U to enable FSR in game
_prepare_gamescope()
{
  if command -v gamescope > /dev/null; then
    # gamescope
    # https://github.com/Plagman/gamescope
    #
    # Run games in Fullscreen at the nested resolution (which should be shown as the only FS res)
    # FSR is between 0 (max) and 20 (min) instead of 0-5. Default is 2 => 8
    #
    # NOTE: Shouldn't crash if the environment sets SDL_VIDEODRIVER=x11
    #
    # NOTE: If we only provide a height, gamescope will assume the width as 16x9
    #
    # NOTE: ReadyOrNot has a minimum of 1368x768, change the config file and do not touch settings to have it be lower
    #       If you open the settings in game, your FPS will go to 2.
    #
    # NOTE: Slay the Spire won't launch in Fullscreen if the resolution is below 1280x720, use Windowed mode
    #
    # NOTE: FSR performance is 2.0x nested resolution.
    # NOTE: FSR balanced is 1.7x nested resolution.
    # NOTE: FSR quality is 1.5x nested resolution.
    #
    # NOTE: Do not apply any FSR sharpness with gamescope, we will use vkBasalt for that
    # NOTE: Shell math doesn't like decimals, so divide stuff by 10 instead
    output_width=1920
    output_height=1080
    if [ -n "${GAME_RES}" ]; then
      output_width="$(printf -- '%s' "${GAME_RES}" | tr 'x' ' ' | awk '{ print $1 }')"
      output_height="$(printf -- '%s' "${GAME_RES}" | tr 'x' ' ' | awk '{ print $2 }')"
      window_type="--borderless"
      unset GAME_RES
    elif [ "${__hostname}" = "nerd1" ]; then
      window_type="--borderless"
    elif [ "${__hostname}" = "nerd2" ]; then
      window_type="--fullscreen"
    else
      return 1
    fi

    # Options passed to gamescope session
    __gamescope_options="${__gamescope_options} --output-width ${output_width} --output-height ${output_height}"
    __gamescope_options="${__gamescope_options} ${window_type}"

    # If a game supports FSR natively, pass `GAME_FSR=1` to the environment when running
    # gametime so that gamescope will not apply its rougher implementation of FSR1.
    if [ -n "${GAME_FSR}" ] || [ "${GAME_FSR}" -ne 0 ]; then
      unset GAME_FSR

      # The game implements its own FSR, but we need all the help we can get.
      # Double FSR us first from 900p to 1080p using gamescope, and then in the game from 900p via the FSR implementation.
      nested_width=1600
      nested_height=900
    else
      # This game needs our gamescope FSR
      # Since gamescope FSR is only 1x (bad), we use quality mode because it otherwise looks real bad.
      # If a game implements its own native upscaling, use that instead with Balanced or Performance FSR 2x
      nested_width=1368
      nested_height=768
    fi

    __gamescope_options="${__gamescope_options} --nested-width ${nested_width} --nested-height ${nested_height}"
    __gamescope_options="${__gamescope_options} --fsr-upscaling --fsr-sharpness 20"

  fi

  unset output_width
  unset output_height

  unset nested_width
  unset nested_height

  unset window_type

  return 0
}

_enable_vkbasalt()
{
  # vkBasalt
  # https://github.com/DadSchoorse/vkBasalt
  #
  # Use with vkBasalt.conf to enable better CAS in games (gamescope has sharpening but it kinda sux)
  if [ -d "/usr/lib/extensions/vulkan/vkBasalt" ]; then
    __game_environment="${__game_environment} ENABLE_VKBASALT=1"
  fi

  return 0
}

_enable_obs()
{
  # OBS VKCapture
  # https://github.com/nowrep/obs-vkcapture
  #
  # Depending on steam vs others, we set te OBS_VKCAPTURE at a different scope
  if command -v obs-gamecapture > /dev/null; then
    __env_tools="${__env_tools} obs-gamecapture"
  fi

  return 0
}

_enable_mangohud()
{
  # Mangohud
  # https://github.com/flightlessmango/MangoHud#hud-configuration
  #
  # We cannot export MANGOHUD=1 before gamescope as it will crash or not report correctly.
  # We must use gamescope to run mangohud, and then use mangohud to run our command.
  if command -v mangohud > /dev/null; then
    __game_tools="${__game_tools} mangohud --dlsym"

    export MANGOHUD_CONFIG="fps,cpu_temp,gpu_temp,ram,vram,swap,cpu_mhz,core_load,gpu_core_clock,gpu_mem_clock,resolution,show_fps_limit,vkbasalt,gamemode,font_size=18,no_display"
  fi

  return 0
}

_enable_flatpak_options()
{
  # If we are running in steam, add --steam option, otherwise do not (causes weird window issues)
  if [ "${FLATPAK_ID}" = "com.valvesoftware.Steam" ]; then
    if command -v gamescope > /dev/null; then
      __gamescope_options="${__gamescope_options} --steam"
    fi
  fi

  return 0
}

_execute()
{
  printf -- '[gametime] gamescope %s -- env %s %s %s' "${__gamescope_options}" "${__game_environment}" "${__game_tools}" "$*"

  if command -v gamescope > /dev/null; then
    # shellcheck disable=SC2086
    exec ${__env_tools} gamescope ${__gamescope_options} -- env ${__game_environment} ${__game_tools} "$@"
  else
    # shellcheck disable=SC2086
    exec env ${__env_tools} ${__game_environment} ${__game_tools} "$@"
  fi

  return 0
}

main()
{
  if [ -z "${FLATPAK_ID}" ]; then
    printf -- "[gametime] Must run inside flatpak.\n"
    return
  fi

  _get_hostname || {
    printf -- "[gametime] Can't get the machine hostname :( Who am I?"
    return 1
  }

  _export_gaming_environment || {
    printf -- '[gametime] Unable to export gaming environment: "%s"\n' "${__hostname}"
    return 1
  }

  _prepare_gamescope || {
    printf -- '[gametime] Unable to decide window dimensions from hostname: "%s"\n' "${__hostname}"
    return 1
  }

  _enable_obs || {
    printf -- '[gametime] Unable to enable OBS: "%s"\n' "${__hostname}"
    return 1
  }

  _enable_vkbasalt || {
    printf -- '[gametime] Unable to enable vkBasalt: "%s"\n' "${__hostname}"
    return 1
  }

  _enable_mangohud || {
    printf -- '[gametime] Unable to enable mangohud: "%s"\n' "${__hostname}"
    return 1
  }

  _enable_flatpak_options || {
    printf -- '[gametime] Unable to enable specific flatpak options: "%s" "%s"\n' "${FLATPAK_ID}" "${__hostname}"
    return 1
  }

  _execute "$@" || {
    printf -- '[gametime] Failed execute: "%s" "%s"\n' "${FLATPAK_ID}" "${__hostname}"
    return 1
  }
}

main "$@" || exit 1
exit 0
