[Unit]
After=container@beszel-hub.service
Wants=container@beszel-hub.service

[Service]
# We are running in agent mode
Environment=BESZEL_MODE=agent

# Run beszel
ExecStartPre=/bin/test -x /opt/pyamsoft/containers/bin/beszel
ExecStart=/opt/pyamsoft/containers/bin/beszel
