#!/bin/sh

readonly _RCT_STORAGE="${HOME}/games/openrct2/container"
readonly _RCT_PASSWD="poop"

main() {
  park="$1"
  if [ -z "${park}" ]; then
    printf -- 'Pass a path to an OpenRCT2 save game.\n'
    return 1
  fi

  printf -- 'Running dedicated openrct2 container for park: %s\n' "${park}"
  exec podman run --rm \
    --name openrct2 -- hostname openrct2 --pull never \
    --security-opt no-new-privileges:true --cap-drop ALL \
    --mount type=bind,source="${_RCT_STORAGE}",target=/home/openrct2/.config/OpenRCT2 \
    -p 127.0.0.1:11753:11753/tcp \
    -p 127.0.0.1:11753:11753/udp \
    -i -t \
    --health-cmd none \
    --userns keep-id \
    docker.io/openrct2/openrct2-cli \
    host /home/openrct2/.config/OpenRCT2/save/"${park}" --password "${_RCT_PASSWD}"
}

main "$@" || exit 1
exit 0
