#!/bin/sh

# https://wiki.archlinux.org/title/System_time#Update_timezone_every_time_NetworkManager_connects_to_a_network

_auto_timezone() {
  if ! command -v curl >/dev/null; then
    printf -- 'Cannot automatically set timezone without curl.\n'
    return 1
  fi

  if ! command -v timedatectl >/dev/null; then
    printf -- 'Cannot automatically set timezone without timedatectl.\n'
    return 1
  fi

  _zone="$(curl --fail --silent "https://ipapi.co/timezone")"
  if [ -z "${_zone}" ]; then
    printf -- 'Failed to find current timezone.\n'
    return 1
  fi

  timedatectl set-timezone "${_zone}" || return 1
  return 0
}

main() {
  case "$2" in
    connectivity-change)
      _auto_timezone "$@" || return 1
      ;;
  esac

  return 0
}

main "$@" || exit 1
exit 0
