#!/bin/sh

_clear_logs()
{
  rm -rf "${_log_path}" || return 1
  mkdir -p "${_log_path}" || return 1
  return 0
}

_podman_rootful()
{
  touch "${_log_path}/$1" || return 1
  podman stop "$1" >> "${_log_path}/$1" 2>&1
  podman rm "$1" >> "${_log_path}/$1" 2>&1
  "/usr/local/bin/$1" "${_user}" >> "${_log_path}/$1" 2>&1 &
}

_podman_rootless()
{
  touch "${_log_path}/$1" || return 1
  podman stop "$1" >> "${_log_path}/$1" 2>&1
  podman rm "$1" >> "${_log_path}/$1" 2>&1
  "${HOME}/.containers/bin/$1" >> "${_log_path}/$1" 2>&1 &
}

_podman()
{
  # Shared log
  touch "${_log_path}/podman" || return 1

  # If podman does not exist on the path normally,
  # We expect it so add it here
  if ! command -v podman > /dev/null; then
    PATH="/opt/homebrew/bin:${PATH}"
    printf -- 'Added homebrew-bin to PATH for podman\n' >> "${_log_path}/podman"
  fi
  export PATH

  if ! command -v podman > /dev/null; then
    printf -- 'You must install "podman"\n' >> "${_log_path}/podman"
    return 1
  fi

  # Restart podman machine
  podman machine stop >> "${_log_path}/podman" 2>&1 || return 1
  podman machine start >> "${_log_path}/podman" 2>&1 || return 1

  _podman_rootful "adguardhome" || return 1
  _podman_rootless "postgres" || return 1

  return 0
}

_startup_programs()
{
  _podman || {
    # Don't return 1 here, we don't want to die just because podman failed
    printf -- 'podman failed to initialize.\n' >> "${_log_path}/podman"
  }

  open "/Applications/Rectangle.app" || {
    printf -- 'Failed to open Rectangle.\n' >> "${_log_path}/rectangle"
  }

  open "/Applications/Easy Move+Resize.app" || {
    printf -- 'Failed to open Easy Move+Resize.\n' >> "${_log_path}/easy_move_resize"
  }

  open "/Applications/Quicksilver.app" || {
    printf -- 'Failed to open Quicksilver.\n' >> "${_log_path}/quicksilver"
  }

  open "/Applications/iTerm.app" || {
    printf -- 'Failed to open iTerm.\n' >> "${_log_path}/iterm"
  }

  open "/Applications/kdeconnect-indicator.app" || {
    printf -- 'Failed to open kdeconnect.\n' >> "${_log_path}/kdeconnect"
  }

  return 0
}

main()
{
  # MacOS environment
  _log_path="${XDG_CONFIG_HOME:-${HOME}/.config}/MacOS/logs"
  _user="$(id -un)"

  _clear_logs || return 1

  # Wait a little bit
  sleep 5 || return 1

  _startup_programs || return 1

  unset _log_path
  unset _user
  return 0
}

main "$@"
