#!/bin/sh

# Java on MacOS is provided by Jetbrains Toolbox
export JAVA_HOME="${HOME}/Applications/Android Studio.app/Contents/jbr/Contents/Home/"

# Add Android tools to the PATH
PATH="${HOME}/devel/sdk/android/platform-tools:${PATH}"
PATH="${HOME}/devel/sdk/android/cmdline-tools/latest/bin:${PATH}"

# Kotlin tools
PATH="${AS_PATH}/plugins/Kotlin/kotlinc/bin:${PATH}"
export PATH

if [ "$1" = "--shell" ]; then
  shift
  exec bash "$@"
else
  # Launch Android Studio
  exec open "${HOME}/Applications/Android Studio.app" "$@"
fi
