#!/bin/sh

# Java on MacOS is provided by Jetbrains Toolbox
AS_PATH=""
for version in "${HOME}/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/"*; do
  AS_PATH="${version}/Android Studio.app/Contents"
  export JAVA_HOME="${AS_PATH}/jbr/Contents/Home/"
  break
done

if [ -z "${JAVA_HOME}" ]; then
  printf -- 'Could not find JAVA_HOME in %s\n' "${HOME}/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0"
  exit 1
fi

# Add Android tools to the PATH
PATH="${HOME}/devel/sdk/android/platform-tools:${PATH}"
PATH="${HOME}/devel/sdk/android/cmdline-tools/latest/bin:${PATH}"

# Kotlin tools
PATH="${AS_PATH}/plugins/Kotlin/kotlinc/bin:${PATH}"
export PATH

if [ "$1" = "--shell" ]; then
  shift
  exec bash "$@"
else
  # Launch Android Studio
  exec open "${HOME}/Applications/JetBrains Toolbox/Android Studio.app" "$@"
fi
