#!/bin/sh

# A simple $HOME only sandbox that re-writes all environment variables to a directory of choice
#
# This is NOT a security sandbox. This has one simple goal which is to $HOME sandbox gaming apps
readonly _SCRIPT_NAME="gamer"

_check_user() {
  if ! id -u "${_target_user}" >/dev/null 2>&1; then
    printf -- 'Target user %s does not exist!\n' "${_target_user}"
    return 1
  fi

  return 0
}

main() {
  _cmd="$1"
  if [ -z "${_cmd}" ]; then
    _cur_name=$(basename "$0")
    readonly _cur_name
    if [ "${_cur_name}" != "${_SCRIPT_NAME}" ]; then
      _cmd="${_cur_name}"
    else
      printf -- 'Must specify a command to run as %s\n' "${_target_user}"
      return 1
    fi
  else
    shift
  fi

  readonly _target_user="gaming-${_cmd}"
  if ! _check_user; then
    return 1
  fi

  # Run
  xhost +SI:localuser:"${_target_user}" || {
    printf -- 'Failed to grant xhost access to %s\n' "${_target_user}"
    return 1
  }

  # Load pulseaudio over localhost TCP
  _pa_mod="module-native-protocol-tcp"
  if ! pactl list modules | grep -q "${_pa_mod}"; then
    pactl load-module "${_pa_mod}" "listen=127.0.0.1" "port=4712" || {
      printf -- 'Failed to load pactl TCP protocol\n'
      return 1
    }
  fi

  sudo \
    -u "${_target_user}" \
    -i \
    -- \
    env GAMER_GAMESCOPE="${GAMER_GAMESCOPE:-0}" launcher "$@"

  return 0
}

main "$@" || exit 1
exit 0
