# shellcheck shell=bash

case "$-" in
*i*)
  # Continue as normal
  ;;
*)
  # Stop if not running interactively
  return 0
  ;;
esac

_starship() {
  # Starship
  if command -v starship >/dev/null && [ -x "$(command -v starship)" ]; then
    eval "$(starship init bash)" && return 0
  fi

  export PS1='\u in \h in \w
\$ '
  return 0
}

_starship

unset _starship

# vim: set filetype=sh :
