# https://www.kernel.org/doc/Documentation/sysctl/kernel.txt

# disable sysrq
# We don't have any keyboards that can actually input SysRq codes lol
kernel.sysrq = 0

# From CachyOS-Settings
# https://github.com/CachyOS/CachyOS-Settings
kernel.printk = 3 3 3 3
kernel.kexec_load_disabled = 1
kernel.kptr_restrict = 2

# Disable the watchdog
kernel.nmi_watchdog = 0

# Disable splitlock mitigation for proprietary gaming performance
# https://wiki.cachyos.org/configuration/general_system_tweaks/#disabling-split-lock-mitigate
kernel.split_lock_mitigate=0
