# https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

# Harden BPF JIT
net.core.bpf_jit_harden = 2

# https://wiki.archlinux.org/title/Sysctl#Enable_BBR
net.core.default_qdisc = cake
net.ipv4.tcp_congestion_control = bbr

# From CachyOS-Settings
# https://github.com/CachyOS/CachyOS-Settings
#######################################
net.core.netdev_max_backlog = 4096
