# https://www.kernel.org/doc/Documentation/sysctl/vm.txt

# Lower swappiness so that we keep more pages in RAM
vm.swappiness = 10

# From CachyOS-Settings
# https://github.com/CachyOS/CachyOS-Settings
vm.vfs_cache_pressure = 50
vm.dirty_bytes = 268435456
vm.dirty_background_bytes = 67108864
vm.dirty_writeback_centisecs = 1500

# page-cluster controls the number of pages up to which consecutive pages are read in from swap in a single attempt.
# This is the swap counterpart to page cache readahead. The mentioned consecutivity is not in terms of virtual/physical addresses,
# but consecutive on swap space - that means they were swapped out together. (Default is 3)
# increase this value to 1 or 2 if you are using physical swap (1 if ssd, 2 if hdd)
#vm.page-cluster = 0
vm.page-cluster = 1
