# shellcheck shell=bash

# Stop if not running interactively
[[ "$-" != *i* ]] && return

_starship() {
  # Starship
  if command -v starship >/dev/null && [ -x "$(command -v starship)" ]; then
    eval "$(starship init bash)" && return 0
  fi

  export PS1='\u in \h in \w
\$ '
  return 0
}

_starship

unset _starship
