#!/bin/sh

# Delete the gaming user entirely
_user="$1"
if [ -z "${_user}" ]; then
  printf -- '[delete] Need target user to delete\n'
  exit 1
fi

_user="gaming-${_user}"
readonly _user

printf -- '[delete] Completely remove gaming user: %s\n' "${_user}"
exec sudo sh -c 'loginctl kill-user "$1" ; sleep 1 && loginctl disable-linger "$1" ; sleep 1 && userdel -r "$1" && sleep 1 && groupdel "$1"' -- "${_user}"
