#!/bin/sh

# A simple $HOME only sandbox that re-writes all environment variables to a directory of choice
#
# This is NOT a security sandbox. This has one simple goal which is to $HOME sandbox gaming apps
readonly _SCRIPT_NAME="gamer"

_check_user() {
  _check_me="$1"
  if ! id -u "${_check_me}" >/dev/null 2>&1; then
    printf -- '[gamer] Target user %s does not exist!\n' "${_check_me}"

    unset _check_me
    return 1
  fi

  unset _check_me
  return 0
}

main() {
  _cmd="$1"

  # We may have a command manually passed in.
  # If we do not, check the name of the script we are executing as.
  # If the script is not the actual script, then use our aliased
  # name as the command executable.
  #
  # For example, symlinking this script to my-game will pass "my-game" as _cmd
  if [ -z "${_cmd}" ]; then
    _cur_name=$(basename "$0")
    readonly _cur_name
    if [ "${_cur_name}" != "${_SCRIPT_NAME}" ]; then
      _cmd="${_cur_name}"
    else
      printf -- '[gamer] Must specify a command to run as!\n'
      return 1
    fi
  else
    shift
  fi

  _target_user="gaming-${_cmd}"
  if ! _check_user "${_target_user}"; then
    return 1
  fi

  # Do all the setup and teardown as a "normal" user.
  # The only thing gamelaunch should do as a sudo script
  # is call machinectl to open a systemd connected user session as
  # the _target_user
  #
  # See gamelaunch script in /opt/pyamsoft/sbin
  exec sudo /opt/pyamsoft/sbin/gamelaunch "$(id -un)" "${_target_user}" "${_cmd}" "$@"
}

main "$@" || exit 1
exit 0
