#!/bin/sh

NAME="${NAME:-}"

## Defaults

## Private variables
__os_name="$(uname)"
__os_arch="$(uname -m)"

# User
_uid="$(id -u)"
_username="$(id -un)"

## Check host user is root
_is_root() {
  [ "${_uid}" -eq 0 ]
}

## Check host is running Linux
_is_linux() {
  [ "${__os_name}" = "Linux" ]
}

## Check host is MacOS
_is_macos() {
  [ "${__os_name}" = "Darwin" ]
}

## Check machine architecture is x86_64
_is_arch_x86() {
  [ "${__os_arch}" = "x86_64" ]
}

## Check machine architecture is AARCH64
_is_arch_arm() {
  case "${__os_arch}" in
  aarch64 | arm64)
    return 0
    ;;
  *)
    return 1
    ;;
  esac
}

##
# Logs a message with newline, formatting, and a name tag
_log() {
  _msg="$1"
  shift

  printf -- "[%s]: ${_msg}\n" "${NAME}" "$@" || return 1

  unset _msg
  return 0
}

##
# Log a message to stderr
_elog() {
  _log "$@" 1>&2 || return 1
  return 0
}

##
# Ensure a function or command is defined
_has_function() {
  command -v "$1" >/dev/null 2>&1
}
