#!/bin/sh

# Source our common library
# shellcheck source=/opt/pyamsoft/lib/common
. "${PYAMSOFT_PATH}/lib/common"

# Disable file path expansion
set -f

IMAGE="${IMAGE:-}"
TAG="${TAG:-}"

# Fail if a runconfig is not provided. If 0, suggest an optional runconfig location
CONTAINER_REQUIRE_RUNCONF="${CONTAINER_REQUIRE_RUNCONF:-1}"
# Run the container with --init
CONTAINER_REQUIRE_INIT="${CONTAINER_REQUIRE_INIT:-0}"
# Add host gateway, disable if custom networking
CONTAINER_NETWORK_HOST_ROUTE="${CONTAINER_NETWORK_HOST_ROUTE:-1}"
# Run the container network with IPv6 if using a custom isolated network
CONTAINER_NETWORK_IP6="${CONTAINER_NETWORK_IP6:-0}"
# Pull policy
CONTAINER_PULL_POLICY="${CONTAINER_PULL_POLICY:-}"
# Custom Entrypoint
CONTAINER_ENTRYPOINT="${CONTAINER_ENTRYPOINT:-}"
# Read only root filesystem
CONTAINER_READONLY="${CONTAINER_READONLY:-0}"
# Use the "unique" name instead of adopting $NAME
CONTAINER_UNIQUE_NAME="${CONTAINER_UNIQUE_NAME:-0}"
# Allow healthchecks (noisy disk write spam when going to journal)
CONTAINER_HEALTHCHECK_ALLOWED="${CONTAINER_HEALTHCHECK_ALLOWED:-0}"
# Run as daemon
CONTAINER_DAEMON="${CONTAINER_DAEMON:-0}"
# Include busybox for container debugging
CONTAINER_DEBUG="${CONTAINER_DEBUG:-0}"
# Use our own machine is the DNS resolver
CONTAINER_DNS_RESOLVER="${CONTAINER_DNS_RESOLVER:-1}"

# Will be evaluated once main() is ran
CONTAINER_RUNTIME_DIR=""
CONTAINER_NETWORK=""
CONTAINER_ENV=""
CONTAINER_MOUNTS=""
CONTAINER_PORTS=""
CONTAINER_CAPS=""
CONTAINER_USERNS=""
CONTAINER_RC=""
CONTAINER_LOGS=""
CONTAINER_MEMORY=""
CONTAINER_CPU=""
CONTAINER_ARGS=""

# The container runtime command
CONTAINER_CMD="${CONTAINER_CMD:-}"

### Private
__container_version=""

## Defaults

## Check if container is "podman"
_is_podman() {
  [ "${CONTAINER_CMD}" = "podman" ]
}

## Check if container is "docker"
_is_docker() {
  [ "${CONTAINER_CMD}" = "docker" ]
}

## Check if container is "container" (on MacOS)
_is_macos_container() {
  _is_macos && [ "${CONTAINER_CMD}" = "container" ]
}

## Check if CMD is atleast version "$1"
_is_cmd_version_atleast() {
  _expect_v="$1"

  if [ -z "${__container_version}" ]; then
    __container_version="$("${CONTAINER_CMD}" --version 2>/dev/null)"
  fi

  # Fun with awk :)
  #
  # - make sure the version string is numbers and dots
  # - split the the HAS by . -> h
  # - split the the EXPECT by . -> e
  # - if h (X.Y.Z) >= e (X.Y.Z) we are good
  __VCMP_HAS="${__container_version}" __VCMP_EXP=${_expect_v} awk 'BEGIN {
    if (!match(ENVIRON["__VCMP_HAS"], /[0-9+(\.[0-9]+)+/)) {
      exit 0;
    }

    split(substr(ENVIRON["__VCMP_HAS"], RSTART, RLENGTH), h, ".");
    split(ENVIRON["__VCMP_EXP"], e, ".");
    for (i = 1; i <= 3; ++i) {
      if (h[i] == "" || e[i] == "") {
        exit 0;
      }

      if (h[i] + 0 > e[i] + 0) {
        exit 0;
      }

      if (h[i] + 0 > e[i] + 0) {
        exit 1;
      }
    }

    exit 0;
  }'

  return "$?"
}

##
# Add to MOUNTS
_add_mounts() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --mounts argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_MOUNTS="${CONTAINER_MOUNTS}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to NETWORK
_add_network() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --network argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_NETWORK="${CONTAINER_NETWORK}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to ENV
_add_env() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --env argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_ENV="${CONTAINER_ENV}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to PORTS
_add_ports() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --ports argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_PORTS="${CONTAINER_PORTS}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to CAPS
_add_caps() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --caps argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_CAPS="${CONTAINER_CAPS}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to USERNS
_add_userns() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --userns argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_USERNS="${CONTAINER_USERNS}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to RC
_add_rc() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --rc argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_RC="${CONTAINER_RC}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to MEMORY
_add_memory() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --memory argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_MEMORY="${CONTAINER_MEMORY}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to CPU
_add_cpu() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --cpu argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_CPU="${CONTAINER_CPU}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to LOGS
_add_logs() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --logs argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_LOGS="${CONTAINER_LOGS}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Add to RC
_add_args() {
  for _arg in "$@"; do
    case "${_arg}" in
    *'
'*)
      _elog 'Invalid newline in --args argument "%s"' "${_arg}"
      return 1
      ;;
    esac

    CONTAINER_ARGS="${CONTAINER_ARGS}
${_arg}"
    unset _arg
  done
  unset _arg

  return 0
}

##
# Various arguments may NOT be available if the container is setup to use inter-container networking
# --network="container:<something>"
# --network="host"
#
# $1 the filter, like "host" or "container:*"
_has_network() {
  _has_cn=0
  _has_previous_network_arg=0
  for _net_arg in ${CONTAINER_NETWORK}; do
    # We want the glob to evaluate for things like 'container:*'
    # shellcheck disable=SC2254
    case "${_net_arg}" in
    --network=$1)
      # We have container networking, do NOT add hostname
      _has_previous_network_arg=0
      _has_cn=1
      break
      ;;
    --network)
      _has_previous_network_arg=1
      ;;
    $1)
      if [ "${_has_previous_network_arg}" -eq 1 ]; then
        # We have container networking, do NOT add hostname
        _has_cn=1
        break
      fi
      _has_previous_network_arg=0
      ;;
    *)
      _has_previous_network_arg=0
      ;;
    esac
    unset _net_arg
  done
  unset _net_arg
  unset _has_previous_network_arg

  if [ "${_has_cn}" -eq 0 ]; then
    unset _has_cn
    # False
    return 1
  else
    unset _has_cn
    # True
    return 0
  fi
}

_require_root() {
  if ! _is_root; then
    _elog 'You must run this as a rootfull container'
    return 1
  fi

  return 0
}

_require_nonroot() {
  if _is_root; then
    _elog 'You must run this as a rootless container'
    return 1
  fi

  return 0
}

##
# Create a new isolated bridge network
_network_isolate() {
  _network_name="${1:-${NAME}}"

  # Create our own network
  if _is_podman; then
    # Podman can "ignore" networks with the same name
    if [ "${CONTAINER_NETWORK_IP6}" -ne 0 ]; then
      "${CONTAINER_CMD}" network create --ignore --driver bridge --opt isolate=true --disable-dns --ipv6 -- "${_network_name}" >/dev/null || {
        _elog "Failed to create isolated network using %s -> %s" "${CONTAINER_CMD}" "${_network_name}"
        unset _network_name
        return 1
      }
    else
      "${CONTAINER_CMD}" network create --ignore --driver bridge --opt isolate=true --disable-dns -- "${_network_name}" >/dev/null || {
        _elog "Failed to create isolated network using %s -> %s" "${CONTAINER_CMD}" "${_network_name}"

        unset _network_name
        return 1
      }
    fi
  elif _is_macos_container; then
    if ! "${CONTAINER_CMD}" network ls --format 'table' | awk '{ print $1 }' | grep -q "^${_network_name}$"; then
      # MacOS has no driver configuration or isolation or anything really.
      # Also no IPv6 specifics
      "${CONTAINER_CMD}" network create "${_network_name}" >/dev/null || {
        _elog "Failed to create isolated network using %s -> %s" "${CONTAINER_CMD}" "${_network_name}"

        unset _network_name
        return 1
      }
    fi
  else
    # Docker must make sure the network doesn't already exist
    if ! "${CONTAINER_CMD}" network ls --format '{{.Name}}' | grep -qx "^${_network_name}$"; then
      if [ "${CONTAINER_NETWORK_IP6}" -ne 0 ]; then
        "${CONTAINER_CMD}" network create --driver bridge --opt com.docker.network.bridge.enable_icc=false --ipv6 -- "${_network_name}" >/dev/null || {
          _elog "Failed to create isolated network using %s -> %s" "${CONTAINER_CMD}" "${_network_name}"

          unset _network_name
          return 1
        }
      else
        "${CONTAINER_CMD}" network create --driver bridge --opt com.docker.network.bridge.enable_icc=false -- "${_network_name}" >/dev/null || {
          _elog "Failed to create isolated network using %s -> %s" "${CONTAINER_CMD}" "${_network_name}"

          unset _network_name
          return 1
        }
      fi
    fi
  fi

  # Attach our isolated network
  _add_network --network="${_network_name}"

  unset _network_name
  return 0
}

##
# Make a directory on the host
_host_mkdir() {
  _mount_d="$1"

  mkdir -p "${_mount_d}" || {
    _elog "Failed to create mount source %s" "${_mount_d}"

    unset _mount_d
    return 1
  }

  unset _mount_d
  return 0
}

##
# chmod a file or directory on the host
_host_chmod() {
  _chmod_mode="$1"
  _chmod_target="$2"

  chmod -R "${_chmod_mode}" "${_chmod_target}" || {
    _elog "Failed to chmod host directory %s (%s)" "${_chmod_target}" "${_chmod_mode}"
    unset _chmod_mode
    unset _chmod_target
    return 1
  }

  unset _chmod_mode
  unset _chmod_target
  return 0
}

##
# Bind most a host directory
_mount_bind() {
  _mount_src="$1"
  _mount_target="$2"
  _mount_options="$3"

  _host_mkdir "${_mount_src}" || {
    unset _mount_src
    unset _mount_target
    unset _mount_options
    return 1
  }

  if [ -n "${_mount_options}" ]; then
    _add_mounts --mount "type=bind,source=${_mount_src},target=${_mount_target},${_mount_options}"
  else
    _add_mounts --mount "type=bind,source=${_mount_src},target=${_mount_target}"
  fi

  unset _mount_src
  unset _mount_target
  unset _mount_options
  return 0
}

##
# Private
__require_function() {
  if ! _has_function "$1"; then
    _elog 'Function is required: %s' "$1"
    return 1
  fi

  return 0
}

##
# Private
__setup_network() {
  _prep_network || return 1

  # Evaluate this AFTER so that just incase the script
  # has changed CONTAINER_NETWORK_HOST_ROUTE from _prep_network, we will pick it up
  if [ "${CONTAINER_NETWORK_HOST_ROUTE}" ] && [ "${CONTAINER_NETWORK_HOST_ROUTE}" -ne 0 ]; then
    if _has_network 'container:*'; then
      _log 'Ignoring host routes. Container networking is already set.'
    elif ! _is_macos_container; then
      _add_network --add-host "localhost:127.0.0.1"
      _add_network --add-host "host.containers.internal:host-gateway"
      _add_network --add-host "host.docker.internal:host-gateway"
    fi
  fi

  return 0
}

##
# Private
__await_directory() {
  _awaiting="$1"
  if [ -z "${_awaiting}" ]; then
    _elog 'Must provide directory to await'
    return 1
  fi

  # Run a simple version command which should "start" the podman container runtime directory
  __container_version="$("${CONTAINER_CMD}" --version 2>/dev/null)" || {
    _elog 'Unable to check %s version.' "${CONTAINER_CMD}"
    return 1
  }

  if _is_linux && _is_podman; then
    # Wait for the podman folder to be available before launching
    # This folder is created "at some point" in response to podman commands being run
    _await_tries=0
    while [ ! -d "${_awaiting}" ]; do
      if [ "${_await_tries}" -ge 30 ]; then
        _elog 'Timed out after waiting for container runtime at %s' "${_awaiting}"
        unset _await_tries
        unset _awaiting
        return 1
      fi

      sleep 1 || {
        _elog 'Cancelled while waiting for container runtime to stand up at %s' "${_awaiting}"

        unset _await_tries
        unset _awaiting
        return 1
      }
    done
    unset _await_tries

    _log 'Container runtime is ready at %s: start %s' "${_awaiting}" "${NAME}"
  fi

  unset _awaiting
  return 0
}

##
# Private
__do_prep_mounts() {
  _prep_mounts || return 1

  # Mount host busybox into container
  if [ "${CONTAINER_DEBUG}" ] && [ "${CONTAINER_DEBUG}" -ne 0 ]; then
    if _has_function busybox; then
      _busybox_target="/run/busybox"
      _log 'Attach busybox for container debugging at %s' "${_busybox_target}"
      _add_mounts --mount "type=bind,source=$(command -v busybox),target=${_busybox_target}"
      unset _busybox_target
    else
      _elog 'Container debugging requested but busybox not available'
    fi
  fi
}

##
# Overridable
#
# Last minute changes
__do_finalize() {
  _finalize "$@" || return 1

  # Use our own recursive DNS (point containers to host 127.0.0.1:53)
  if [ -n "${CONTAINER_DNS_RESOLVER}" ] && [ "${CONTAINER_DNS_RESOLVER}" -eq 1 ]; then
    _has_dns=0
    for _net_arg in ${CONTAINER_NETWORK}; do
      case "${_net_arg}" in
      --dns | --dns=*)
        # We have our own DNS
        _has_dns=1
        break
        ;;
      *)
        ;;
      esac
      unset _net_arg
    done
    unset _net_arg

    if _has_network host; then
      _log 'Ignoring local DNS resolver - host networking already set'
    elif _has_network 'container:*'; then
      _log 'Ignoring local DNS resolver - container networking already set'
    elif [ "${_has_dns}" -eq 0 ]; then
      # Add the "container local DNS"
      # Many images hardcode Google which is lame.
      # Avoid the Google upstream by strictly opting into one DNS
      _local_dns=""

      # Only guaranteed for podman `pasta` ?
      if _is_podman; then
        _local_dns="169.254.1.1"
      fi

      if [ -n "${_local_dns}" ]; then
        _log 'Using local DNS resolver at %s' "${_local_dns}"
        _add_network --dns "${_local_dns}"
      else
        _elog 'Unable to discover the "container DNS resolver". Using image defaults'
      fi
      unset _local_dns
    else
      _log 'Ignoring local DNS resolver - custom DNS already set'
    fi
  fi
  unset _has_dns
}

##
# Overridable
#
# Default function for setting up Memory usage
_prep_memory() {
  if _is_linux; then
    # 80% of total ram
    _allow_ram_mb="$(awk '/^MemTotal:/ { print int($2 / 1024 * 8 / 10) }' /proc/meminfo)"

    if [ -n "${_allow_ram_mb}" ] && [ "${_allow_ram_mb}" -gt 0 ]; then
      _add_memory --memory "${_allow_ram_mb}M"
    else
      _elog 'Unable to read total RAM from /proc/meminfo. No memory limits.'
    fi

    unset _allow_ram_mb
  fi

  return 0
}

##
# Overridable
#
# Default function for setting up CPU usage
_prep_cpu() {
  if _is_linux; then
    _cpu_number="$(getconf _NPROCESSORS_ONLN)"

    if [ -n "${_cpu_number}" ] && [ "${_cpu_number}" -gt 2 ]; then
      # If we have more than 2 cores, allow a container to use most
      _add_cpu --cpus "$((_cpu_number - 2))"
    else
      # Otherwise, allocate a single core allowance
      _add_cpu --cpus 1
    fi
  fi

  unset _cpu_number
  return 0
}

##
# Overridable
#
# Default function for setting up system logging
_prep_log() {
  # On Linux, our user session executes from systemd and thus sets the systemd vars
  # like JOURNAL_STREAM and INVOCATION_ID
  #
  # We cannot reliably use them to sniff "am I being ran by systemd"
  #
  # As such our services set a special PYAM_SYSTEMD variable and we sniff that
  if _is_linux && [ -n "${PYAM_SYSTEMD}" ]; then
    if _is_podman; then
      _add_logs --log-driver journald
    elif _is_docker; then
      _add_logs --log-driver local
    fi
  fi

  # Disable healthchecks
  if [ "${CONTAINER_HEALTHCHECK_ALLOWED}" -eq 0 ]; then
    if ! _is_macos_container; then
      _add_logs --no-healthcheck
    fi
  fi

  return 0
}

##
# Overridable
#
# Default function for sourcing a run configuration
_prep_rc() {
  # Source the runtime config (so we don't have to hardcode keys)
  _runconf="${CONTAINER_RUNTIME_DIR}/${NAME}/runconfig.env"
  if [ -n "${CONTAINER_REQUIRE_RUNCONF}" ] && [ "${CONTAINER_REQUIRE_RUNCONF}" -ne 0 ]; then
    if [ ! -e "${_runconf}" ]; then
      _elog 'You must provide %s' "${_runconf}"
      return 1
    fi
  else
    if [ ! -e "${_runconf}" ]; then
      _log 'Optional runconf supported at %s' "${_runconf}"
    fi
  fi

  if [ -e "${_runconf}" ]; then
    # Don't follow symlinks
    if [ -L "${_runconf}" ]; then
      _elog '%s must be a regular file.' "${_runconf}"
      unset _runconf
      return 1
    fi

    # Must be owned by current user
    if _is_macos; then
      _owner_uid="$(stat -f %u "${_runconf}")"
      _perm="$(stat -f %Lp "${_runconf}")"
    else
      _owner_uid="$(stat -c %u "${_runconf}")"
      _perm="$(stat -c %a "${_runconf}")"
    fi
    if [ "${_owner_uid}" != "${_uid}" ]; then
      _elog '%s must be owned by current user %s != %s' "${_runconf}" "${_owner_uid}" "${_uid}"
      unset _owner_uid
      return 1
    fi

    # Must not be writable by group/others
    # *[2367][0-7] catches group-write (second-to-last digit in write set)
    # *[2367]      catches others-write (last digit in write set)
    case "${_perm}" in
    *[2367][0-7] | *[2367])
      _elog '%s permissions too open. Must only be writable by owner %s (%s)' "${_runconf}" "${_owner_uid}" "${_perm}"
      unset _owner_uid
      unset _perm
      return 1
      ;;
    esac
    unset _perm
    unset _owner_uid

    # Source the file into the environment
    # shellcheck disable=SC1090
    . "${_runconf}" || {
      _elog 'Unable to source runconfig %s' "${_runconf}"
      return 1
    }
  fi
  unset _runconf

  return 0
}

##
# Overridable
#
# Last minute changes
_finalize() {
  return 0
}

##
# Overridable
#
# Default execution function
# Restricts capabilities, privileges, and ensures the container is named and removed after execution
_containerize() {
  if [ -n "${CONTAINER_REQUIRE_INIT}" ] && [ "${CONTAINER_REQUIRE_INIT}" -ne 0 ]; then
    _add_rc --init
  fi

  if [ -n "${CONTAINER_READONLY}" ] && [ "${CONTAINER_READONLY}" -ne 0 ]; then
    _add_rc --read-only
  fi

  if [ -n "${CONTAINER_ENTRYPOINT}" ]; then
    _add_rc --entrypoint="${CONTAINER_ENTRYPOINT}"
  fi

  if [ -n "${CONTAINER_PULL_POLICY}" ]; then
    _add_rc --pull="${CONTAINER_PULL_POLICY}"
  fi

  # Set a standard name if we do NOT want a unique one
  if [ -z "${CONTAINER_UNIQUE_NAME}" ] || [ "${CONTAINER_UNIQUE_NAME}" -eq 0 ]; then
    _add_rc --name="${NAME}"
  fi

  # Breaks on MacOS with a complaint about "unrecognized key ''"
  if _is_linux; then
    # Disable detach keys
    _add_rc --detach-keys=""
  fi

  # Security
  if ! _is_macos_container; then
    _add_rc --security-opt=no-new-privileges
  fi
  _add_rc --cap-drop=ALL

  if _is_podman; then
    if _is_cmd_version_atleast 5.4; then
      # Slightly increase security by starting with a blank hosts file
      _add_network --hosts-file="none"
    fi
  fi

  # MacOS has no hostname
  if ! _is_macos_container; then
    # podman can always set a hostname
    if _is_podman; then
      _add_rc --hostname="${NAME}"
    else
      # Docker must be sure we are not in a container network namespace
      if ! _has_network 'container:*'; then
        _add_rc --hostname="${NAME}"
      fi
    fi
  fi

  # If we are running in systemd
  if [ -n "${PYAM_SYSTEMD}" ]; then
    # We always daemonize and setup a notify signal
    if _is_podman; then
      _add_rc --detach
      _add_rc --sdnotify=conmon
    else
      # Docker has no --sdnotify
      #
      # This is not perfect since the container is not technically live yet.
      systemd-notify --ready || {
        _elog 'Failed to notify systemd of container launch'
        return 1
      }
    fi
  else
    # Running directly

    # Daemonize
    if [ -n "${CONTAINER_DAEMON}" ] && [ "${CONTAINER_DAEMON}" -eq 1 ]; then
      _add_rc --detach
    elif [ -t 0 ]; then
      # Or attach tty stdin
      # As long as we have a terminal
      _add_logs -i
      _add_logs -t
    fi
  fi

  # Make the IFS into newline only so we can correctly parse arguments with embedded spaces
  IFS='
'

  # Log the commands we use next
  # Fail on errors
  # Fail on unassigned
  set -xeu

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  exec "${CONTAINER_CMD}" \
    run \
    --rm \
    ${CONTAINER_RC} \
    ${CONTAINER_MEMORY} \
    ${CONTAINER_CPU} \
    ${CONTAINER_LOGS} \
    ${CONTAINER_NETWORK} \
    ${CONTAINER_ENV} \
    ${CONTAINER_MOUNTS} \
    ${CONTAINER_PORTS} \
    ${CONTAINER_CAPS} \
    ${CONTAINER_USERNS} \
    "${IMAGE}:${TAG}" \
    ${CONTAINER_ARGS} \
    "$@"
}

_load_containers() {
  if [ -z "${CONTAINER_CMD}" ]; then
    # Use podman, don't use docker
    if _has_function podman; then
      CONTAINER_CMD="podman"
    elif _has_function docker; then
      CONTAINER_CMD="docker"
    else
      if _is_macos; then
        if _has_function container; then
          CONTAINER_CMD="container"
        fi
      fi
    fi
  fi

  readonly CONTAINER_CMD

  _supported=0
  if [ -n "${CONTAINER_CMD}" ]; then
    if _is_podman || _is_docker; then
      _supported=1
    else
      if _is_macos; then
        if _is_macos_container; then
          _supported=1
        fi
      fi
    fi
  fi

  if [ "${_supported}" -ne 1 ]; then
    if _is_macos; then
      _elog 'Requires either "podman" "docker", or "container" (MacOS specific) ("podman" preferred)'
    else
      _elog 'Requires either "podman" or "docker" ("podman" preferred)'
    fi
    unset _supported
    return 1
  fi

  unset _supported
}

main() {
  # Reset
  CONTAINER_LOGS=""
  CONTAINER_RC=""
  CONTAINER_RUNTIME_DIR=""
  CONTAINER_NETWORK=""
  CONTAINER_ENV=""
  CONTAINER_MOUNTS=""
  CONTAINER_PORTS=""
  CONTAINER_CAPS=""
  CONTAINER_USERNS=""
  CONTAINER_MEMORY=""
  CONTAINER_CPU=""
  CONTAINER_ARGS=""

  _load_containers || return 1

  if [ -z "${NAME}" ]; then
    # shellcheck disable=SC2016
    printf -- '[container-launch] $NAME must be defined\n'
    return 1
  fi

  if [ -z "${IMAGE}" ]; then
    # shellcheck disable=SC2016
    _elog '$IMAGE must be defined'
    return 1
  fi

  if [ -z "${TAG}" ]; then
    # shellcheck disable=SC2016
    _elog '$TAG must be defined'
    return 1
  fi

  # Move to accessible directory
  if _is_root; then
    _watch="/run/containers"
    CONTAINER_RUNTIME_DIR="/usr/local/etc/containers"

    cd / || {
      _elog 'Unable to move into / directory'
      return 1
    }
  else
    _watch="${XDG_RUNTIME_DIR:-"/run/user/${_uid}"}/containers"
    CONTAINER_RUNTIME_DIR="${HOME}/.local/etc/containers"

    cd "${HOME}" || {
      _elog 'Unable to move into HOME directory'
      return 1
    }
  fi

  __require_function _check_user || return 1
  _check_user || return 1

  __require_function _prep_mounts || return 1
  __do_prep_mounts || return 1

  __require_function _prep_ports || return 1
  _prep_ports || return 1

  __require_function _prep_caps || return 1
  _prep_caps || return 1

  __require_function _prep_network || return 1
  __setup_network || return 1

  __require_function _prep_env || return 1
  _prep_env || return 1

  # These are defined here an while they can be overridden, they should
  # always exist
  _prep_cpu || return 1
  _prep_memory || return 1
  _prep_log || return 1
  _prep_rc || return 1

  __await_directory "${_watch}" || return 1
  __do_finalize "$@" || return 1

  _containerize "$@" || return 1
  return 0
}
