#!/bin/sh

# scrutiny v0.7.1 ships with a web folder that has assets
# that cannot be read because the directory doesn't have
# exec permission, so icons don't load.
#
# Fix it by going in before init, and then let init take over
# after

# Mark the assets folder executable so we can go into it
chmod +X -R /opt/scrutiny/web/assets

# But now it can be read by everyone, take away group and other
chmod go= -R /opt/scrutiny/web/assets

# Now go!
exec /init
