#!/usr/bin/sh

# In scrutiny v0.8.0, /bin/sh does not exist.
# /usr/bin/sh is where shell lives. What the hell?

# scrutiny v0.7.1-v0.8.0 ships with a web folder that has assets
# that cannot be read because the directory doesn't have
# exec permission, so icons don't load.
#
# Fix it by going in before init, and then let init take over
# after

# Mark the assets folder executable so we can go into it
chmod +X -R /opt/scrutiny/web/assets

# But now it can be read by everyone, take away group and other
chmod go= -R /opt/scrutiny/web/assets

# Update the smart database before we get started
# Use no-verify since we do not have GPG installed in the container
update-smart-drivedb --no-verify && {
  # And copy the updated one out of /var/lib/smartmontools/drivedb to /usr/share/smartmontools/ just in case
  cp /var/lib/smartmontools/drivedb/drivedb.h /usr/share/smartmontools/ || {
    printf -- 'Failed to copy updated drivedb.h\n'
  }
}

# Now go!
exec /init
