version: "3"

.security: &security
  cap_drop:
    - "ALL"
  security_opt:
    - "no-new-privileges:true"

.network: &network
  add_host:
    - "localhost:127.0.0.1"
    - "nerd2:100.77.161.9"
    - "host.containers.internal:host-gateway"
  dns:
    - "1.1.1.1"
  dns_search:
    - "."

.caps: &caps
  cap_add:
    - "CHOWN"
    - "DAC_OVERRIDE"
    - "FOWNER"
    - "SETGID"
    - "SETUID"

services:
  meilisearch:
    image: docker.io/getmeili/meilisearch:v1.7.4

    <<: *network
    <<: *security

    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./meilisearch:/meili_data

  redis:
    image: docker.io/redis:7.2.4

    <<: *caps
    <<: *network
    <<: *security

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 3s
      retries: 30

  bar-assistant:
    image: docker.io/barassistant/server:3.11.0

    <<: *caps
    <<: *network
    <<: *security

    # Needed for podman
    user: "0:0"
    userns_mode: keep-id

    depends_on:
      meilisearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Needed for podman
      - PUID=1002
      - PGID=1004

      - APP_URL=$API_URL
      - LOG_CHANNEL=stderr
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
      - ALLOW_REGISTRATION=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/www/cocktails/storage/bar-assistant
      - ./logs:/var/www/cocktails/storage/logs

  salt-rim:
    image: docker.io/barassistant/salt-rim:2.11.0

    <<: *caps
    <<: *network
    <<: *security

    depends_on:
      bar-assistant:
        condition: service_healthy
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - BAR_NAME=$BAR_NAME
      - DESCRIPTION=$BAR_DESCRIPTION
      - DEFAULT_LOCALE=en-US
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 5s
      retries: 5

  nginx:
    image: docker.io/nginx:1.24.0

    <<: *caps
    <<: *network
    <<: *security

    depends_on:
      bar-assistant:
        condition: service_healthy
      salt-rim:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    ports:
      - 127.0.0.1:3000:3000/tcp
      - 100.77.161.9:3000:3000/tcp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
