#!/bin/sh

main() {
  cscli lapi status && {
    printf -- 'Crowdsec is still alive!\n'
    curl -s 'http://localhost:3001/api/push/fOIUXAmHT4?status=up&msg=OK&ping=' || {
      printf -- 'Failed to ping Uptime Kuma'
      return 1
    }

    return 0
  }

  return 1
}

main "$@" || exit 1
exit 0
