#!/bin/sh

readonly _name="caddy"
readonly _image="ghcr.io/caddybuilds/caddy-cloudflare"
readonly _tag="2.10.2"

# Use podman, don't use docker
if command -v podman >/dev/null; then
  _cmd="podman"
elif command -v docker >/dev/null; then
  _cmd="docker"
else
  printf -- 'Requires either "podman" or "docker" ("podman" preferred)\n'
  exit 1
fi
readonly _cmd

readonly CONTAINER_RUNTIME_DIR="/.local/etc/containers"

_prep_mounts() {
  readonly _mount1="${CONTAINER_RUNTIME_DIR}/${_name}/data"
  readonly _mount2="${CONTAINER_RUNTIME_DIR}/${_name}/config"
  readonly _mount3="${CONTAINER_RUNTIME_DIR}/${_name}/serve"
  readonly _mount4="${CONTAINER_RUNTIME_DIR}/${_name}/logs"

  _runas mkdir -p "${_mount1}" || return 1
  _runas mkdir -p "${_mount2}" || return 1
  _runas mkdir -p "${_mount3}" || return 1
  _runas mkdir -p "${_mount4}" || return 1

  _mounts=""
  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/data"
  _mounts="${_mounts} --mount type=bind,source=${_mount2},target=/config"
  _mounts="${_mounts} --mount type=bind,source=${_mount3},target=/serve"
  _mounts="${_mounts} --mount type=bind,source=${_mount4},target=/var/log/caddy"

  _caddyfile="/etc/caddy"
  if [ -d "${_caddyfile}" ]; then
    _mounts="${_mounts} --mount type=bind,source=${_caddyfile},target=/etc/caddy"
  fi
  unset _caddyfile

  _binary="/opt/caddy/bin/caddy"
  if [ -f "${_binary}" ]; then
    _mounts="${_mounts} --mount type=bind,source=${_binary},target=/usr/bin/caddy"
  fi
  unset _binary

  readonly _mounts
  return 0
}

_prep_caps() {
  _caps=""
  _caps="${_caps} --cap-add NET_BIND_SERVICE"
  _caps="${_caps} --cap-add NET_ADMIN"

  if [ "$(uname)" = "Darwin" ]; then
    _caps="${_caps} --cap-add DAC_OVERRIDE"
  fi

  readonly _caps
  return 0
}

_prep_ports() {
  _ports=""

  # Bind to a non-priv port and force redirect via firewall DNAT
  _ports="${_ports} -p 127.0.0.1:3080:3080/tcp"
  _ports="${_ports} -p 127.0.0.1:3443:3443/tcp"

  readonly _ports
  return 0
}

_check_user() {
  if [ "$(id -u)" -eq 0 ]; then
    printf -- 'You must run this as a non-root container\n'
    return 1
  fi

  # Expects to be root (since the cert file is owned by root)
  _userns=""
  if [ "${_cmd}" = "podman" ]; then
    _userns="${_userns} --userns keep-id"
  fi

  readonly _userns
}

_containerize() {
  # Runtime configuration
  _cd=""

  # Source the runtime config (so we don't have to hardcode keys)
  _runconf="${CONTAINER_RUNTIME_DIR}/${_name}/runconfig.env"
  if [ ! -e "${_runconf}" ]; then
    printf -- 'You must provide %s\n' "${_runconf}"
    return 1
  fi

  # Source the file into the environment
  # shellcheck disable=SC1090
  . "${_runconf}" || return 1
  unset _runconf

  # On Linux, our user session executes from systemd and thus sets the systemd vars
  # like JOURNAL_STREAM and INVOCATION_ID
  #
  # We cannot reliably use them to sniff "am I being ran by systemd"
  #
  # As such our services set a special PYAM_SYSTEMD variable and we sniff that
  if [ "$(uname)" = "Linux" ] && [ -n "${PYAM_SYSTEMD}" ]; then
    if [ "${_cmd}" = "podman" ]; then
      _cd="${_cd} --log-driver json-file"
    fi
  else
    _cd="${_cd} -i -t"
  fi
  readonly _cd

  # We use our container DNS resolver
  # MacOS can't launch with host-gateway
  # On Linux we run systemd-resolved on our host machine for DNS caching
  _network="--add-host localhost:127.0.0.1 --dns-search=."
  if [ "$(uname)" = "Linux" ] && [ "${_cmd}" = "podman" ]; then
    _network="${_network} --add-host host.containers.internal:host-gateway"
  fi

  # Host networking for now until we figure out how to NAT route everyone in
  _network="${_network} --net=host"

  readonly _network

  # Auto Update Checking support
  _auto="--label=io.containers.autoupdate=registry"
  _auto="${_auto} --label=PODMAN_SYSTEMD_UNIT=not-a-real.service"
  readonly _auto

  # Log the commands we use next
  # Fail on errors
  # Fail on unassigned
  set -xeu

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  exec ${_cmd} run --rm \
    --name "${_name}" --hostname "${_name}" \
    --security-opt no-new-privileges:true --cap-drop ALL \
    ${_cd} \
    ${_network} \
    ${_auto} \
    ${_mounts} \
    ${_ports} \
    ${_caps} \
    ${_userns} \
    "${_image}:${_tag}" "$@"
}

main() {
  _check_user || return 1
  _prep_mounts || return 1
  _prep_ports || return 1
  _prep_caps || return 1
  _prep_env || return 1

  "${_cmd}" --version >/dev/null 2>&1 || {
    printf -- 'Unable to check %s version.\n' "${_cmd}"
    return 1
  }

  # Wait for the ${XDG_RUNTIME_DIR}/podman folder to be available before launching
  # This folder is created "at some point" in response to podman commands being run
  if [ "$(uname)" = "Linux" ] && [ "${_cmd}" = "podman" ]; then
    while [ ! -d "${XDG_RUNTIME_DIR}/containers" ]; do
      sleep 1 || {
        printf -- 'Cancelled while waiting for container runtime to stand up.\n'
        return 1
      }
    done
    printf -- 'Container runtime is ready, start %s\n' "${_name}"
  fi

  _containerize "$@" || return 1
  return 0
}

main "$@" || exit 1
exit 0
