#!/bin/sh

# Source our common library
. "/opt/pyamsoft/lib/container-launch"

NAME="crowdsec"
IMAGE="docker.io/crowdsecurity/crowdsec"
# -debian images support journalctl
TAG="v1.7.4-debian"

##
# lapi - Crowdsec LAPI central instance
# agent - Agent instance, no LAPI
#   - Requires runconfig.env to contain credentials
case "${CROWDSEC_MODE}" in
lapi | agent) ;;
*)
  _log 'Must run with CROWDSEC_MODE set to one of "lapi" "agent"'
  exit 1
  ;;
esac

_prep_mounts() {
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/config" "/etc/crowdsec" || return 1
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/data" "/var/lib/crowdsec/data" || return 1

  # Bouncers should live at their real directory for systemd service scripts to handle them
  if [ -d "/etc/crowdsec/bouncers" ]; then
    CONTAINER_MOUNTS="${CONTAINER_MOUNTS} --mount type=bind,source=/etc/crowdsec/bouncers,target=/etc/crowdsec/bouncers"
  fi

  return 0
}

_prep_env() {
  if [ "${CROWDSEC_MODE}" = "agent" ]; then
    CONTAINER_ENV="${CONTAINER_ENV} -e USE_WAL=true"
    CONTAINER_ENV="${CONTAINER_ENV} -e NO_HUB_UPGRADE=true"
    CONTAINER_ENV="${CONTAINER_ENV} -e DISABLE_LOCAL_API=true"
  fi

  return 0
}

_prep_network() {
  if [ "${CROWDSEC_MODE}" = "lapi" ]; then
    # TODO(Peter): This used to work without --host
    # The LAPI machine must use host networking or else it hangs when downloading hub updates for some reason.
    CONTAINER_NETWORK="${CONTAINER_NETWORK} --network=host"
  else
    _network_isolate || return 1
  fi

  return 0
}

_prep_caps() {
  if [ "${CROWDSEC_MODE}" = "lapi" ]; then
    # Server needs these caps to launch
    CONTAINER_CAPS="${CONTAINER_CAPS} --cap-add SETUID"
    CONTAINER_CAPS="${CONTAINER_CAPS} --cap-add SETGID"
    CONTAINER_CAPS="${CONTAINER_CAPS} --cap-add DAC_OVERRIDE"
  fi

  return 0
}

_prep_ports() {
  CONTAINER_PORTS="${CONTAINER_PORTS} -p 127.0.0.1:7080:7080/tcp"
  CONTAINER_PORTS="${CONTAINER_PORTS} -p 127.0.0.1:6060:6060/tcp"

  return 0
}

_check_user() {
  if [ "$(uname)" = "Darwin" ]; then
    _log 'Not supported on MacOS'
    return 1
  else
    if [ "$(id -u)" -ne 0 ]; then
      _log 'You must run this as a rootful container'
      return 1
    fi
  fi

  # Expects to be root (since the cert file is owned by root)
  CONTAINER_USERNS="--user 0:0"

  return 0
}

main "$@" || exit 1
exit 0
