#!/bin/sh

_PROG="$(basename "$0")"
readonly _PROG

_log() {
  _msg="$1"
  shift

  printf -- "[%s]: ${_msg}\n" "${_PROG}" "$@" || return 1

  unset _msg
  return 0
}

_elog() {
  _log "$@" 1>&2 || return 1
  return 0
}

_post() {
  exec curl -s -X POST -H "Authorization: Bearer ${BEARER_TOKEN}" "$1?success=$2"
}

main() {
  _unescape=0
  if [ "$1" = "--unescape" ]; then
    _unescape=1
    shift
  fi

  if [ -z "$1" ]; then
    _elog 'You must pass a heartbeat URL!'
    return 1
  fi

  _url="$1"
  shift

  if [ "${_unescape}" -eq 1 ]; then
    _log 'Unescape URL: %s' "${_url}"
    _url="$(systemd-escape --unescape "${_url}")"
  fi

  /opt/pyamsoft/bin/cscli lapi status && {
    _log 'Crowdsec is still alive! Report: %s' "${_url}"
    _post "${_url}" "true" || {
      _elog 'Failed to ping Heartbeat URL, but Crowdsec is alive: "%s"' "${_url}"
      return 1
    }

    return 0
  }

  _post "${_url}" "false" || {
    _elog 'Failed to ping Heartbeat URL, and Crowdsec is dead: "%s"' "${_url}"
  }

  # Restart the crowdsec service
  _log 'Crowdsec LAPI is down, restart the container service...'
  systemctl restart container@crowdsec.service || {
    _elog 'Failed to restart the Crowdsec container.'
  }

  return 0
}

main "$@" || exit 1
exit 0
