#!/bin/sh

readonly _name="crowdsec"
readonly _image="docker.io/crowdsecurity/crowdsec"

# -debian images support journalctl
readonly _tag="v1.7.4-debian"

_log() {
  _msg="$1"
  shift

  printf -- "[%s]: ${_msg}\n" "${_name}" "$@" || return 1

  unset _msg
  return 0
}

##
# lapi - Crowdsec LAPI central instance
# agent - Agent instance, no LAPI
#   - Requires runconfig.env to contain credentials
case "${CROWDSEC_MODE}" in
lapi | agent) ;;
*)
  _log 'Must run with CROWDSEC_MODE set to one of "lapi" "agent"'
  exit 1
  ;;
esac

# Use podman, don't use docker
if command -v podman >/dev/null; then
  _cmd="podman"
elif command -v docker >/dev/null; then
  _cmd="docker"
else
  _log 'Requires either "podman" or "docker" ("podman" preferred)'
  exit 1
fi
readonly _cmd

readonly CONTAINER_RUNTIME_DIR="/usr/local/etc/containers"

_prep_mounts() {
  readonly _mount1="${CONTAINER_RUNTIME_DIR}/${_name}/config"
  readonly _mount2="${CONTAINER_RUNTIME_DIR}/${_name}/data"

  mkdir -p "${_mount1}" || {
    _log "Failed to create mount source %s" "${_mount1}"
    return 1
  }
  mkdir -p "${_mount2}" || {
    _log "Failed to create mount source %s" "${_mount2}"
    return 1
  }

  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/etc/crowdsec"
  _mounts="${_mounts} --mount type=bind,source=${_mount2},target=/var/lib/crowdsec/data"

  # Bouncers should live at their real directory for systemd service scripts to handle them
  if [ -d "/etc/crowdsec/bouncers" ]; then
    _mounts="${_mounts} --mount type=bind,source=/etc/crowdsec/bouncers,target=/etc/crowdsec/bouncers"
  fi

  readonly _mounts
  return 0
}

_prep_env() {
  _env=""

  readonly _env
  return 0
}

_prep_network() {
  _network=""

  if [ "${CROWDSEC_MODE}" = "lapi" ]; then
    # TODO(Peter): This used to work without --host
    # The LAPI machine must use host networking or else it hangs when downloading hub updates for some reason.
    _network="${_network} --net=host"
  else
    # We use our container DNS resolver
    # MacOS can't launch with host-gateway
    _network="${_network} --add-host localhost:127.0.0.1 --dns-search=."
    _network="${_network} --add-host host.containers.internal:host-gateway"

    # Create our own network
    if [ "${_cmd}" = "podman" ]; then
      # Podman can "ignore" networks with the same name
      "${_cmd}" network create --ignore --driver bridge --opt isolate=true --disable-dns -- "${_name}" >/dev/null 2>&1 || {
        _log "Failed to create isolated network using %s" "${_cmd}"
        return 1
      }
    else
      # Docker must make sure the network doesn't already exist
      if ! "${_cmd}" network ls --format '{{.Name}}' | grep -q "${_name}"; then
        "${_cmd}" network create --driver bridge --opt com.docker.network.bridge.enable_icc=false -- "${_name}" >/dev/null 2>&1 || {
          _log "Failed to create isolated network using %s" "${_cmd}"
          return 1
        }
      fi
    fi

    # Attach our isolated network
    _network="${_network} --net=${_name}"
  fi

  readonly _network
  return 0
}

_prep_log() {
  _logs=""
  # On Linux, our user session executes from systemd and thus sets the systemd vars
  # like JOURNAL_STREAM and INVOCATION_ID
  #
  # We cannot reliably use them to sniff "am I being ran by systemd"
  #
  # As such our services set a special PYAM_SYSTEMD variable and we sniff that
  if [ "$(uname)" = "Linux" ] && [ -n "${PYAM_SYSTEMD}" ]; then
    if [ "${_cmd}" = "podman" ]; then
      _logs="${_logs} --log-driver json-file"
    fi
  else
    _logs="${_logs} -i -t"
  fi

  readonly _logs
  return 0
}

_prep_caps() {
  _caps=""

  # Agent and Server containers can use different CAPS, see runconfig
  # https://www.redhat.com/en/blog/secure-your-containers-one-weird-trick

  readonly _caps
  return 0
}

_prep_ports() {
  _ports=""

  _ports="${_ports} -p 127.0.0.1:7080:7080/tcp"
  _ports="${_ports} -p 127.0.0.1:6060:6060/tcp"

  readonly _ports
  return 0
}

_check_user() {
  if [ "$(uname)" = "Darwin" ]; then
    _log 'Not supported on MacOS'
    return 1
  else
    if [ "$(id -u)" -ne 0 ]; then
      _log 'You must run this as a rootful container'
      return 1
    fi
  fi

  # Expects to be root (since the cert file is owned by root)
  _userns="--user 0:0"

  readonly _userns
}

_containerize() {
  # Runtime configuration
  _cs=""

  # Source the runtime config (so we don't have to hardcode keys)
  _runconf="${CONTAINER_RUNTIME_DIR}/${_name}/runconfig.env"
  if [ ! -e "${_runconf}" ]; then
    _log 'You must provide %s' "${_runconf}"
    return 1
  fi

  # Source the file into the environment
  # shellcheck disable=SC1090
  . "${_runconf}" || {
    _log 'Unable to source %s' "${_runconf}"
    return 1
  }
  unset _runconf
  readonly _cs

  # Log the commands we use next
  # Fail on errors
  # Fail on unassigned
  set -xeu

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  exec ${_cmd} run --rm \
    --name "${_name}" --hostname "${_name}" \
    --cap-drop=ALL --security-opt no-new-privileges:true \
    ${_cs} \
    ${_network} \
    ${_env} \
    ${_logs} \
    ${_mounts} \
    ${_ports} \
    ${_caps} \
    ${_userns} \
    "${_image}:${_tag}" "$@"
}

main() {
  _check_user || return 1
  _prep_mounts || return 1
  _prep_ports || return 1
  _prep_caps || return 1
  _prep_env || return 1
  _prep_log || return 1
  _prep_network || return 1

  # Launch the containers runtime
  "${_cmd}" --version >/dev/null 2>&1 || {
    _log 'Unable to check %s version.' "${_cmd}"
    return 1
  }

  if [ "$(uname)" = "Linux" ] && [ "${_cmd}" = "podman" ]; then
    # Wait for the root /run/podman folder to be available before launching
    # This folder is created "at some point" in response to podman commands being run
    while [ ! -d "/run/containers" ]; do
      sleep 1 || {
        _log 'Cancelled while waiting for container runtime to stand up.'
        return 1
      }
    done
    _log 'Container runtime is ready, start %s' "${_name}"
  fi

  _containerize "$@" || return 1
  return 0
}

main "$@" || exit 1
exit 0
