#!/bin/sh

# Source our common library
. "/opt/pyamsoft/lib/container-launch"

NAME="crowdsec"
IMAGE="docker.io/crowdsecurity/crowdsec"
# -debian images support journalctl
TAG="v1.7.6-debian"

CONTAINER_MEMORY_LIMIT="1G"

##
# lapi - Crowdsec LAPI central instance
# agent - Agent instance, no LAPI
#   - Requires runconfig.env to contain credentials
case "${CROWDSEC_MODE}" in
lapi | agent) ;;
*)
  _elog 'Must run with CROWDSEC_MODE set to one of "lapi" "agent"'
  exit 1
  ;;
esac

_prep_mounts() {
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/config" "/etc/crowdsec" || return 1
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/data" "/var/lib/crowdsec/data" || return 1

  # Bouncers should live at their real directory for systemd service scripts to handle them
  _bouncers="/etc/crowdsec/bouncers"
  if [ -d "${_bouncers}" ]; then
    _mount_bind "${_bouncers}" "${_bouncers}" || return 1
  fi
  unset _bouncers

  return 0
}

_prep_env() {
  _add_env -e NO_HUB_UPGRADE=true

  if [ "${CROWDSEC_MODE}" = "agent" ]; then
    _add_env -e USE_WAL=true
    _add_env -e DISABLE_LOCAL_API=true
  fi

  return 0
}

_prep_network() {
  # TODO(Peter): This used to work without --host
  # The machine must use host networking or else it hangs when downloading hub updates for some reason.
  _add_network --network="host"

  return 0
}

_prep_caps() {
  if [ "${CROWDSEC_MODE}" = "lapi" ]; then
    # Server needs these caps to launch
    _add_caps --cap-add SETUID
    _add_caps --cap-add SETGID
    _add_caps --cap-add DAC_OVERRIDE
  fi

  return 0
}

_prep_ports() {
  # Drop localhost port binding, we don't need local machine access
  # _add_ports -p "127.0.0.1:7080:7080/tcp"
  # _add_ports -p "127.0.0.1:6060:6060/tcp"

  return 0
}

_check_user() {
  if _is_macos; then
    _elog 'Not supported on MacOS'
    return 1
  fi

  _require_root || return 1

  # Expects to be root (since the cert file is owned by root)
  _add_userns --user "0:0"

  return 0
}

main "$@" || exit 1
exit 0
