#!/bin/sh

_clean() {
  rm -rf ./dots ./pkg ./src ./testing
}

_makepkg() {
  if [ "$1" = "install" ]; then
    makepkg -sfci || return 1
  else
    makepkg -sfc || return 1
  fi

  return 0
}

main() {
  _clean

  _makepkg "$1" || return 1

  if [ "$1" = "test" ]; then
    mkdir "./testing"
    cd "./testing" || {
      printf -- 'Failed to cd in to testing\n'
      return 1
    }

    mv ../pyamsoft-settings*.tar.zst .
    tar xvf ./*.tar.zst
    cd .. || {
      printf -- 'Failed to cd out of testing\n'
      return 1
    }
  fi

  _clean

  return 0
}

main "$@" || exit 1
exit 0
