#!/bin/sh

# Variables
__gamescope_options=""
__game_environment=""
__game_tools=""
__env_tools=""

_log() {
  _msg="$1"

  if [ -n "${_msg}" ]; then
    shift
  fi

  # shellcheck disable=SC2059
  printf -- "[gametime]: ${_msg}\n" "$@"
}

_prepare_env() {
  # Use single-file shader cache
  # https://www.phoronix.com/news/Mesa-Single-File-Cache
  export MESA_DISK_CACHE_SINGLE_FILE=1
  __game_environment="${__game_environment} MESA_DISK_CACHE_SINGLE_FILE=${MESA_DISK_CACHE_SINGLE_FILE}"

  # Force VRS shading
  # https://www.phoronix.com/review/radeon-radv-vrs
  export RADV_FORCE_VRS="2x2"
  __game_environment="${__game_environment} RADV_FORCE_VRS=${RADV_FORCE_VRS}"

  # Disable vertical blank
  export vblank_mode=0
  __game_environment="${__game_environment} vblank_mode=${vblank_mode}"

  # These SDL vars can cause random issues with some Steam games, so unset them
  # SDL2, 1.2 compat
  # SDL3 adds underscores lol
  export SDL_VIDEODRIVER=
  export SDL_AUDIODRIVER=
  export SDL_VIDEO_DRIVER="${SDL_VIDEODRIVER}"
  export SDL_AUDIO_DRIVER="${SDL_AUDIODRIVER}"
  __game_environment="${__game_environment} SDL_VIDEODRIVER=${SDL_VIDEODRIVER}"
  __game_environment="${__game_environment} SDL_VIDEO_DRIVER=${SDL_VIDEO_DRIVER}"
  __game_environment="${__game_environment} SDL_AUDIODRIVER=${SDL_AUDIODRIVER}"
  __game_environment="${__game_environment} SDL_AUDIO_DRIVER=${SDL_AUDIO_DRIVER}"

  # Don't close the window
  export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
  __game_environment="${__game_environment} SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=${SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS}"

  # Wayland caling mode none (default stretch)
  export SDL_VIDEO_WAYLAND_MODE_SCALING=none
  __game_environment="${__game_environment} SDL_VIDEO_WAYLAND_MODE_SCALING=${SDL_VIDEO_WAYLAND_MODE_SCALING}"

  # Optional fixes for messy graphics
  if [ -n "${GAME_FIX}" ] && [ "${GAME_FIX}" -ne 0 ]; then
    _log 'Applying AMD driver fixes: YES (GAME_FIX=%s)' "${GAME_FIX}"

    # Fix weird texture bugs
    # https://github.com/Plagman/gamescope/issues/320
    export AMD_DEBUG=nodcc
    __game_environment="${__game_environment} AMD_DEBUG=${AMD_DEBUG}"

    export RADV_DEBUG=nodcc
    __game_environment="${__game_environment} RADV_DEBUG=${RADV_DEBUG}"
  else
    _log 'Applying AMD driver fixes: NO (GAME_FIX=%s)' "${GAME_FIX}"
  fi

  unset GAME_FIX
  return 0
}

_get_hostname() {
  if command -v hostname >/dev/null; then
    __hostname="$(hostname)"
  elif command -v hostnamectl >/dev/null && [ -n "${XDG_RUNTIME_DIR}" ]; then
    __hostname="$(hostnamectl hostname)"
  fi

  return 0
}

##
# For gamescope, the following is needed
# --devices=all;shm; is needed for Steam overlay and Steam input
# --env SDL_VIDEODRIVER=x11 must be set on the flatpak itself, not just in this file.
# You must use Proton-GE from within a flatpak, since Steam pressure-vessel messes up gamescope
# You must use Super+U to enable FSR in game
_prepare_gamescope() {
  # gamescope
  # https://github.com/Plagman/gamescope
  #
  # Run games in Fullscreen at the nested resolution (which should be shown as the only FS res)
  # FSR is between 0 (max) and 20 (min) instead of 0-5. Default is 2 => 8
  #
  # NOTE: If we only provide a height, gamescope will assume the width as 16x9
  #
  # NOTE: FSR performance is 2.0x nested resolution. (20)
  # NOTE: FSR balanced is 1.7x nested resolution. (17)
  # NOTE: FSR quality is 1.5x nested resolution. (15)
  # NOTE: FSR ultra-quality is 1.3x nested resolution. (13)
  #
  # NOTE: Shell math doesn't like decimals, so divide stuff by 10 instead
  #
  ####
  #
  # NOTE: ReadyOrNot has a minimum of 1368x768, change the config file and do not touch settings to have it be lower
  #       If you open the settings in game, your FPS will go to 2.
  #       Run it with GAME_FSR=13
  #
  # NOTE: Slay the Spire won't launch in Fullscreen if the resolution is below 1280x720, use Windowed mode
  #       Or run it with GAME_FSR=15

  # Defaults to 1080p windowed
  window_type=""
  output_height=1080
  output_width=
  fsr_amount=15
  fps_max=300

  if [ "${__hostname}" = "nerd1" ]; then
    _log 'Using %s gamescope defaults' "${__hostname}"
  elif [ "${__hostname}" = "nerd2" ]; then
    _log 'Using %s gamescope defaults' "${__hostname}"
    window_type="--fullscreen"
  else
    _log 'Hostname "%s" unknown, use gamescope defaults' "${__hostname}"
  fi

  if [ -n "${GAME_WINDOW}" ]; then
    window_type="${GAME_WINDOW}"
  fi

  # If an output resolution is defined as GAME_RES=WxH, then use it here
  if [ -n "${GAME_RES}" ]; then
    output_width="$(printf -- '%s' "${GAME_RES}" | tr 'x' ' ' | awk '{ print $1 }')"
    output_height="$(printf -- '%s' "${GAME_RES}" | tr 'x' ' ' | awk '{ print $2 }')"
  fi

  # If we have a custom GAME_FSR amount passed in, use it
  if [ -n "${GAME_FSR}" ]; then
    fsr_amount="${GAME_FSR}"
  fi

  # If we have a custom GAME_FPS amount passed in, use it
  if [ -n "${GAME_FPS}" ]; then
    fps_max="${GAME_FPS}"
  fi

  # Calculate the nested resolution by mathing the set fsr_amount
  # fsr_amount of 0 means no FSR
  nested_height=
  nested_width=
  if [ "${fsr_amount}" -eq 0 ]; then
    # Game has its own FSR, or does not want FSR
    nested_height="${output_height}"
    if [ -n "${output_width}" ]; then
      nested_width="${output_width}"
    fi
  else
    # Calculate nested resolution by applying FSR
    nested_height="$((output_height * 10 / fsr_amount))"
    if [ -n "${output_width}" ]; then
      nested_width="$((output_width * 10 / fsr_amount))"
    fi
  fi

  # Options passed to gamescope session
  __gamescope_options="${__gamescope_options} ${window_type} --output-height ${output_height} --nested-height ${nested_height}"

  # Scale the window to fill
  #
  # Scaling causes the mouse to not be in the right place
  #__gamescope_options="${__gamescope_options} --scaler fill"

  # Apply most sharpness through gamescope so it works for OpenGL
  # Then use vkBasalt for any slight extra
  # 0 is max sharpness, 20 is min sharpness
  # Slight sharpness by default and drop vkbasalt by default
  __gamescope_options="${__gamescope_options} --filter fsr --fsr-sharpness 16"

  # Force cursor grab to keep cursor in focus on Wayland
  __gamescope_options="${__gamescope_options} --force-grab-cursor"

  # Due to gamescope limiter issues, FPS limit should be double the refresh rate
  # https://github.com/ValveSoftware/gamescope/issues/995
  #
  # Just set something that's so high it won't bother us - limit FPS via in-game options
  __gamescope_options="${__gamescope_options} --nested-refresh ${fps_max}"
  __gamescope_options="${__gamescope_options} --nested-unfocused-refresh 15"

  # Expose Wayland
  if [ -n "${GAME_WAYLAND}" ] && [ "${GAME_WAYLAND}" -ne 0 ] && [ -n "${XDG_SESSION_TYPE}" ] && [ "${XDG_SESSION_TYPE}" = "wayland" ]; then
    _log 'Running with Wayland exposed'
    __gamescope_options="${__gamescope_options} --expose-wayland"
  else
    # Setup for WAYLAND for gamescope-wl
    # Gamescope crashes sometimes if you are NOT using wayland and this is undefined
    #
    # Don't use or else gamescope complains about wayland
    #
    # if [ -z "${WAYLAND_DISPLAY}" ]; then
    #   export WAYLAND_DISPLAY=""
    #   __game_environment="${__game_environment} WAYLAND_DISPLAY=${WAYLAND_DISPLAY}"
    # fi
    unset WAYLAND_DISPLAY

    # Use the SDL backend
    #
    # Otherwise we run with gamescope-wl on wayland, but we want normal gamescope
    _log 'Force running with SDL backend'
    __gamescope_options="${__gamescope_options} --backend sdl"
  fi

  if [ -n "${output_width}" ]; then
    __gamescope_options="${__gamescope_options} --output-width ${output_width}"
  fi
  if [ -n "${nested_width}" ]; then
    __gamescope_options="${__gamescope_options} --nested-width ${nested_width}"
  fi

  _log 'gamescope renderer: YES (GAME_RES=%s, GAME_FSR=%s, GAME_WINDOW=%s)' "${GAME_RES}" "${GAME_FSR}" "${GAME_WINDOW}"

  unset output_width
  unset output_height
  unset nested_width
  unset nested_height
  unset window_type
  unset fps_max
  unset GAME_RES
  unset GAME_FSR
  unset GAME_WINDOW
  unset GAME_FPS
  return 0
}

# vkBasalt
# https://github.com/DadSchoorse/vkBasalt
#
# Use with vkBasalt.conf to enable better CAS in games (gamescope has sharpening but it kinda sux)
_prepare_vkbasalt() {
  if [ -d "/usr/lib/extensions/vulkan/vkBasalt" ]; then
    if [ -n "${GAME_VKB}" ] && [ "${GAME_VKB}" -ne 0 ]; then
      __game_environment="${__game_environment} ENABLE_VKBASALT=1"
      _log 'vkBasalt post processing: YES (GAME_VKB=%s)' "${GAME_VKB}"
    else
      _log 'vkBasalt post processing: NO (GAME_VKB=%s)' "${GAME_VKB}"
    fi
  else
    _log 'vkBasalt post processing: MISSING (GAME_VKB=%s)' "${GAME_VKB}"
  fi

  unset GAME_VKB
  return 0
}

# Zink OpenGL
# https://wiki.archlinux.org/title/OpenGL#OpenGL_over_Vulkan_(Zink)
_prepare_zink() {
  if [ -n "${GAME_ZINK}" ] && [ "${GAME_ZINK}" -ne 0 ]; then
    _log 'Zink for OpenGL over Vulkan: YES (GAME_ZINK=%s)' "${GAME_ZINK}"
    __game_environment="${__game_environment} __GLX_VENDOR_LIBRARY_NAME=mesa"
    __game_environment="${__game_environment} MESA_LOADER_DRIVER_OVERRIDE=zink"
    __game_environment="${__game_environment} GALLIUM_DRIVER=zink"
  else
    _log 'Zink for OpenGL over Vulkan: NO (GAME_ZINK=%s)' "${GAME_ZINK}"
  fi

  unset GAME_ZINK
  return 0
}

# Mangohud
# https://github.com/flightlessmango/MangoHud
_prepare_mangohud() {
  _mangohud_config="fps,frametime,cpu_temp,gpu_temp,ram,vram,swap,cpu_mhz,gpu_core_clock,gpu_mem_clock,resolution,show_fps_limit,vkbasalt,gamemode,fsr,font_size=18,width=400"

  if command -v mangohud >/dev/null; then
    if [ -n "${GAME_HUD}" ] && [ "${GAME_HUD}" -ne 0 ]; then
      _log 'MangoHud performance overlay: YES (GAME_HUD=%s)' "${GAME_HUD}"
      export MANGOHUD_CONFIG="${_mangohud_config}"
      __game_tools="${__game_tools} mangohud --dlsym"
    else
      _log 'MangoHud performance overlay: NO (GAME_HUD=%s)' "${GAME_HUD}"
    fi
  else
    _log 'MangoHud performance overlay: MISSING (GAME_HUD=%s)' "${GAME_HUD}"
  fi

  unset _mangohud_config
  unset GAME_HUD
  return 0
}

_prepare_gamemode() {
  if command -v gamemoderun >/dev/null; then
    if [ -n "${GAME_MODE}" ] && [ "${GAME_MODE}" -eq 1 ]; then
      _log 'Feral gamemode: YES (GAME_MODE=%s)' "${GAME_MODE}"
      __env_tools="${__env_tools} gamemoderun"
      __game_tools="${__game_tools} gamemoderun"
    else
      _log 'Feral gamemode: NO (GAME_MODE=%s)' "${GAME_MODE}"
    fi
  else
    _log 'Feral gamemode: MISSING (GAME_MODE=%s)' "${GAME_MODE}"
  fi

  unset GAME_MODE
  return 0
}

# OBS VKCapture
# https://github.com/nowrep/obs-vkcapture
#
# Depending on steam vs others, we set te OBS_VKCAPTURE at a different scope
_prepare_obs() {
  if command -v obs-gamecapture >/dev/null; then
    if [ -n "${GAME_OBS}" ] && [ "${GAME_OBS}" -ne 0 ]; then
        __env_tools="${__env_tools} obs-gamecapture"
        _log 'OBS Game Capture: YES (GAME_OBS=%s)' "${GAME_OBS}"
      else
        _log 'OBS Game Capture: NO (GAME_OBS=%s)' "${GAME_OBS}"
      fi
  else
    _log 'OBS Game Capture: MISSING (GAME_OBS=%s)' "${GAME_OBS}"
  fi

  unset GAME_OBS
}

_prepare() {
  _log 'Preparing gaming environment...'

  _prepare_env || return 1
  _prepare_gamemode || return 1
  _prepare_obs || return 1
  _prepare_vkbasalt || return 1
  _prepare_zink || return 1
  _prepare_mangohud || return 1

  return 0
}

_enable_flatpak_options() {
  # If we are running in steam, add --steam option, otherwise do not (causes weird window issues)
  if [ "${FLATPAK_ID}" = "com.valvesoftware.Steam" ]; then
    __gamescope_options="${__gamescope_options} --steam"
    _log 'Steam specific gamescope options: YES'
  else
    _log 'Steam specific gamescope options: NO'
  fi

  return 0
}

_execute() {
  unset __hostname

  _log '%s %s %s -- env %s %s %s' \
    "${__env_tools}" "${_gamescope}" "${__gamescope_options}" "${__game_environment}" "${__game_tools}" "$*"

  # shellcheck disable=SC2086
  exec ${__env_tools} ${_gamescope} ${__gamescope_options} -- env ${__game_environment} ${__game_tools} "$@"

  return 0
}

main() {
  _log 'Using gamescope'
  _gamescope="gamescope"

  _get_hostname || {
    _log 'Unable to resolve hostname'
    __hostname=""
  }

  _prepare || {
    _log 'Unable to prepare gaming environment'
    return 1
  }

  _prepare_gamescope || {
    _log 'Unable to prepare gamescope'
    return 1
  }

  _enable_flatpak_options || {
    _log 'Unable to enable specific flatpak options'
    return 1
  }

  _execute "$@" || {
    _log 'gametime] Failed execute'
    return 1
  }
}

main "$@" || exit 1
exit 0
