#!/bin/sh

# Source our common library
. "/opt/pyamsoft/lib/container-launch"

NAME="scrutiny"
IMAGE="ghcr.io/analogj/scrutiny"
TAG="v0.8.1-omnibus"

_prep_mounts() {
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/config" "/opt/scrutiny/config" || return 1
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/db" "/opt/scrutiny/influxdb" || return 1
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/logs" "/opt/scrutiny/logs" || return 1
  _mount_bind "${CONTAINER_RUNTIME_DIR}/${NAME}/entrypoints" "/entrypoints" || return 1

  # Needs udev from host
  CONTAINER_MOUNTS="${CONTAINER_MOUNTS} --mount type=bind,source=/run/udev,target=/run/udev,ro"

  return 0
}

_prep_caps() {
  # For smartctl
  CONTAINER_CAPS="${CONTAINER_CAPS} --cap-add SYS_RAWIO"

  # Work with NVME
  CONTAINER_CAPS="${CONTAINER_CAPS} --cap-add SYS_ADMIN"

  return 0
}

_prep_env() {
  return 0
}

_prep_network() {
  _network_isolate || return 1

  return 0
}

_prep_ports() {
  CONTAINER_PORTS="${CONTAINER_PORTS} -p 127.0.0.1:8081:8080/tcp"
  CONTAINER_PORTS="${CONTAINER_PORTS} -p 127.0.0.1:8086:8086/tcp"
  return 0
}

_check_user() {
  _require_root || return 1

  # Expects to be root
  CONTAINER_USERNS="${CONTAINER_USERNS} --user=0:0"

  return 0
}

_containerize() {
  # Log the commands we use next
  # Fail on errors
  # Fail on unassigned
  set -xeu

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  exec ${CONTAINER_CMD} run --rm \
    --name "${NAME}" --hostname "${NAME}" \
    --security-opt no-new-privileges:true --cap-drop ALL \
    --entrypoint "/entrypoints/init" \
    ${CONTAINER_MEMORY} \
    ${CONTAINER_RC} \
    ${CONTAINER_LOGS} \
    ${CONTAINER_NETWORK} \
    ${CONTAINER_ENV} \
    ${CONTAINER_MOUNTS} \
    ${CONTAINER_PORTS} \
    ${CONTAINER_CAPS} \
    ${CONTAINER_USERNS} \
    "${IMAGE}:${TAG}" "$@"
}

if _is_macos; then
  _log 'Not supported on MacOS' "${NAME}"
  exit 1
fi

main "$@" || exit 1
exit 0
