#!/bin/sh

readonly _path="nerd@nerd2:/home/nerd/holding"

for f in "$@"; do
  # Remove a trailing space to copy over folders
  _file="${f%/}"
  if command -v sshpass >/dev/null; then
    sshpass -f "${HOME}/.nerd2-passwd" rsync -hrtplu --progress "${_file}" "${_path}"
  else
    rsync -hrtplu --progress "${_file}" "${_path}"
  fi
done

