#!/bin/sh

readonly _name="openrct2-server"
readonly _image="docker.io/openrct2/openrct2-cli"
readonly _tag="0.4.5"

# Use podman, don't use docker
readonly _cmd="podman"

_prep_mounts() {
  readonly _mount1="${HOME}/.local/etc/containers/${_name}/config"

  # Prep the directories
  mkdir -p "${_mount1}" || return 1

  _mounts=""
  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/home/openrct2/.config/OpenRCT2"

  readonly _mounts
  return 0
}

_prep_caps() {
  _caps=""

  readonly _caps
  return 0
}

_prep_ports() {
  _ports=""

  _ports="${_ports} -p 127.0.0.1:11753:11753/tcp"
  _ports="${_ports} -p 127.0.0.1:11753:11753/udp"

  readonly _ports
  return 0
}

_check_user() {
  if [ "$(id -u)" -eq 0 ]; then
    printf -- 'You must run this as a rootless container\n'
    return 1
  fi

  _userns="--userns keep-id"

  readonly _userns

  return 0
}

_containerize() {
  # MacOS can't launch with host-gateway
  _network="--add-host localhost:127.0.0.1 --dns 1.1.1.1 --dns-search=."
  if [ "$(uname)" = "Linux" ]; then
    _network="${_network} --add-host host.containers.internal:host-gateway"
  fi
  readonly _network

  # Log the commands we use next
  # Fail on errors
  # Fail on unassigned
  set -xeu

  # This container uses the gluetun VPN network stack.
  # Gluetun must be running before this container.

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  exec ${_cmd} run ${_how} \
    --name "${_name}" --hostname "${_name}" \
    --security-opt no-new-privileges:true --cap-drop ALL \
    --init \
    ${_network} \
    ${_mounts} \
    ${_ports} \
    ${_caps} \
    ${_userns} \
    "${_image}:${_tag}" \
    host "/home/openrct2/.config/OpenRCT2/${park}" \
    --password "poop" \
    --headless \
    "$@"
}

main() {
  _check_user || return 1
  _prep_mounts || return 1
  _prep_ports || return 1
  _prep_caps || return 1

  # How do we run?
  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
    shift
    _how="-d --restart=unless-stopped"
  else
    _how="--rm -i -t"
  fi
  readonly _how

  park="$1"
  if [ -z "${park}" ]; then
    printf -- 'Pass a path to an OpenRCT2 save game in root: %s.\n' "${_mount1}"
    return 1
  fi
  shift

  # Correct the path if it is absolute
  # Corrects something like ${HOME}/games/openrct2/save/Park.park => save/Park.park
  park="${park#*/openrct2-server/config/}"

  _containerize "$@" || return 1
  return 0
}

main "$@" || exit 1
exit 0
