#!/bin/sh

readonly _name="openrct2-server"
readonly _image="localhost/pyamsoft/openrct2"
readonly _tag="latest" # built from 0.4.7

# Use podman, don't use docker
readonly _cmd="podman"

_prep_mounts() {
  # Park/saves must be in ${_mount1}/save/
  readonly _mount1="${HOME}/.local/etc/containers/${_name}/config"

  # Prep the directories
  mkdir -p "${_mount1}" || return 1

  _mounts=""
  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/home/openrct2/.config/OpenRCT2"

  readonly _mounts
  return 0
}

_prep_caps() {
  _caps=""

  readonly _caps
  return 0
}

_prep_ports() {
  _ports=""

  # Openrct2 only uses TCP. I know. Wow
  _ports="${_ports} -p 127.0.0.1:11753:11753/tcp"

  readonly _ports
  return 0
}

_check_user() {
  if [ "$(id -u)" -eq 0 ]; then
    printf -- 'You must run this as a rootless container\n'
    return 1
  fi

  _userns="--userns keep-id"

  readonly _userns

  return 0
}

_containerize() {
  # OpenRCT2 runtime config variable
  _or=""

  # Source the runtime config (so we don't have to hardcode keys)
  _runconf="${HOME}/.local/etc/containers/${_name}/runconfig.env"
  if [ ! -e "${_runconf}" ]; then
    printf -- 'You must provide %s\n' "${_runconf}"
    return 1
  fi

  # Source the file into the environment
  # shellcheck disable=SC1090
  . "${_runconf}" || return 1
  unset _runconf
  readonly _or

  # Only compare the version minors
  _current_version="$("${_cmd}" --version | awk '{ print $3 }' | tr '.' ' ' | awk '{ print $1 "." $2}')"
  _is_cmd_new_enough="$(printf -- '%s' "${_current_version}" | awk '{ if ($1 >= 4.7) print 1; else print 0 }')"
  unset _current_version

  # MacOS can't launch with host-gateway
  _network="--add-host localhost:127.0.0.1 --dns 1.1.1.1 --dns-search=."
  if [ "$(uname)" = "Linux" ] && [ 1 -eq "${_is_cmd_new_enough}" ]; then
    _network="${_network} --add-host host.containers.internal:host-gateway"
  fi
  readonly _network

  unset _is_cmd_new_enough

  # Log the commands we use next
  # Fail on errors
  # Fail on unassigned
  set -xeu

  # Don't quote so that if user is empty it still expands
  #
  # shellcheck disable=SC2086
  exec ${_cmd} run --rm -i -t \
    --name "${_name}" --hostname "${_name}" \
    --security-opt no-new-privileges:true --cap-drop ALL \
    --init \
    ${_or} \
    ${_network} \
    ${_mounts} \
    ${_ports} \
    ${_caps} \
    ${_userns} \
    "${_image}:${_tag}" \
    host "/home/openrct2/.config/OpenRCT2/${park}" \
    --password "poop" \
    --headless \
    "$@"
}

main() {
  _check_user || return 1
  _prep_mounts || return 1
  _prep_ports || return 1
  _prep_caps || return 1

  # Wait for the ${XDG_RUNTIME_DIR}/podman folder to be available before launching
  # This folder is created "at some point" in response to podman commands being run
  "${_cmd}" --version >/dev/null 2>&1 || {
    printf -- 'Unable to check %s version.\n' "${_cmd}"
    return 1
  }
  while [ ! -d "${XDG_RUNTIME_DIR}/containers" ]; do
    sleep 1 || {
      printf -- 'Cancelled while waiting for container runtime to stand up.\n'
      return 1
    }
  done
  printf -- 'Container runtime is ready, start %s\n' "${_name}"

  park="$1"
  if [ -z "${park}" ]; then
    printf -- 'Pass a path to an OpenRCT2 save game in root: %s.\n' "${_mount1}"
    return 1
  fi
  shift

  # Correct the path if it is absolute
  # Corrects something like ${HOME}/games/openrct2/save/Park.park => save/Park.park
  park="${park#*/openrct2-server/config/}"

  _containerize "$@" || return 1
  return 0
}

main "$@" || exit 1
exit 0
