#!/bin/sh

readonly _target_user="gaming"

_check_user() {
  if  id -u "${_target_user}" >/dev/null 2>&1; then
    printf -- 'Target user %s already exists!\n' "${_target_user}"
    return 1
  fi

  return 0
}

_create_user() {
  printf -- 'Create target user: %s\n' "${_target_user}"
  sudo useradd --create-home --shell /bin/nologin --user-group "${_target_user}" || {
    printf -- 'Unable to create target user: %s\n' "${_target_user}"
    return 1
  }

  sudo mkdir -p /home/"${_target_user}"/.cache
  sudo mkdir -p /home/"${_target_user}"/.config
  sudo mkdir -p /home/"${_target_user}"/.local/share

  printf -- 'Install user bash profile files: %s\n' "${_target_user}"
  sudo cp ./gaming-bashrc /home/"${_target_user}"/.bashrc || {
    printf -- 'Failed to install bashrc for %s\n' "${_target_user}"
    return 1
  }
  sudo cp ./gaming-bash_profile /home/"${_target_user}"/.bash_profile || {
    printf -- 'Failed to install bash_profile for %s\n' "${_target_user}"
    return 1
  }

  # Update access perms
  sudo chown "${_target_user}:${_target_user}" -R /home/"${_target_user}" || {
    printf -- 'Failed to own %s home\n' "${_target_user}"
    return 1
  }
  sudo chmod o-rwx -R /home/"${_target_user}" || {
    printf -- 'Failed to close off %s home to OTHER\n' "${_target_user}"
    return 1
  }
  sudo chmod g+rwX -R /home/"${_target_user}" || {
    printf -- 'Failed to allow %s home to GROUP\n' "${_target_user}"
    return 1
  }
  sudo chmod u+rwX -R /home/"${_target_user}" || {
    printf -- 'Failed to allow %s home to USER\n' "${_target_user}"
    return 1
  }

  printf -- 'Enable linger for user: %s\n' "${_target_user}"
  sudo loginctl enable-linger "${_target_user}" || {
    printf -- 'Failed to enable linger for %s\n' "${_target_user}"
    return 1
  }

  return 0
}

main() {
  if ! _check_user; then
    return 1
  fi

  _create_user || return 1

  return 0
}

main "$@" || exit 1
exit 0
