#!/bin/sh

# Privileged script, to be used with gamer script and sudoers set up

__grant_candidates=""

_check_user() {
  _check_me="$1"
  if ! id -u "${_check_me}" >/dev/null 2>&1; then
    printf -- '[gamelaunch] User %s does not exist!\n' "${_check_me}"

    unset _check_me
    return 1
  fi

  unset _check_me
  return 0
}

_grant_joystick() {
  # Find all candidate input devices
  for _dev in /dev/input/js* /dev/input/event*; do
    # Device must exist and it must identify as a joystick
    if [ -e "${_dev}" ] && udevadm info "${_dev}" | grep -q '^E: ID_INPUT_JOYSTICK=1$' >/dev/null 2>&1; then
      if [ -z "${__grant_candidates}" ]; then
        __grant_candidates="--facl=${_dev}"
      else
        __grant_candidates="--facl=${_dev} ${__grant_candidates}"
      fi
    fi
    unset _dev
  done
  unset _dev

  return 0
}

_execute() {
  _exec_from_user="$1"
  _exec_to_user="$2"

  # Eat arguments, leave rest
  shift
  shift

  # Groups explanation:
  # "pipewire" - Faster sound performance (will still work without but may see more XRUNs)
  #
  # Previous groups
  # "input" - Grants access to Controller/Joystick
  #           Instead of giving entire group (and this would allow keyboard input sniffing, use facl to grant joysticks)
  readonly _extra_groups="pipewire"

  printf -- '[gamelaunch] Running command: "~/bin/launcher %s"\n' "$*"
  printf -- '[gamelaunch] Running command from user: %s\n' "${_exec_from_user}"
  printf -- '[gamelaunch] Running command as user: %s\n' "${_exec_to_user}"
  printf -- '[gamelaunch] Running command with extra groups: %s\n' "${_extra_groups}"

  # Running machinectl shell gives us a "clean session to work with" that attaches to it's own systemctl --user session
  # and loginctl session
  #
  # Because its "clean" though, we need to manually forward our main user session "$DISPLAY" and "$XAUTHORITY"
  # to allow x11 connections.
  #
  # DO NOT FORWARD "$WAYLAND_DISPLAY" yet as multi-user on the same display isn't fully figured out yet (things crash).
  #
  # We want this 'raw ~' to not expand so that it is evaluated as the target_user home, not main_user home
  # shellcheck disable=SC2086,SC2088
  exec /usr/bin/usergrant --from "${_exec_from_user}" --to "${_exec_to_user}" \
    ${__grant_candidates} \
    --x11 --audio -- \
    --property="SupplementaryGroups=${_extra_groups}" \
    --setenv="GAMER_GAMESCOPE=${GAMER_GAMESCOPE:-0}" \
    --setenv="GAMER=1" \
    /bin/bash -l -c '~/bin/launcher' "$@" || return 1
}

main() {
  if [ -z "${SUDO_USER}" ]; then
    printf -- "[gamelaunch] Requires that you run as a regular user with sudo\n"
    return 1
  fi

  if [ "${SUDO_UID}" -eq 0 ]; then
    printf -- "[gamelaunch] Requires that you run as a regular user with sudo\n"
    return 1
  fi

  if [ "$(id -u)" -ne 0 ]; then
    printf -- "[gamelaunch] Requires that you run with sudo\n"
    return 1
  fi

  if [ -z "${DISPLAY}" ]; then
    printf -- "[gamelaunch] Requires a valid \$DISPLAY variable.\n"
    return 1
  fi

  if [ -z "${XAUTHORITY}" ]; then
    printf -- "[gamelaunch] Requires a valid \$XAUTHORITY variable.\n"
    return 1
  fi

  _from_user="$1"
  if [ -z "${_from_user}" ]; then
    printf -- '[gamelaunch] Requires a FROM user as the first argument\n'
    return 1
  fi
  shift

  _to_user="$1"
  if [ -z "${_to_user}" ]; then
    printf -- '[gamelaunch] Requires a TO user as the second argument\n'
    return 1
  fi
  shift

  # Consume gamescope
  case "$1" in
  --gamescope)
    if [ -z "$2" ]; then
      printf -- '[gamelaunch] Missing required --gamescope argument value!\n'
      return 1
    fi

    # Export gamescope
    export GAMER_GAMESCOPE="$2"

    # Eat both
    shift
    shift
    ;;
  --gamescope=*)
    _split="$(printf -- '%s\n' "$1" | tr '=' ' ' | awk '{ print $2 }')"
    if [ -z "${_split}" ]; then
      printf -- '[gamelaunch] Missing required --gamescope= argument value!\n'
      return 1
    fi

    # Export gamescope
    export GAMER_GAMESCOPE="${_split}"
    unset _split

    # Eat just one
    shift
    ;;
  *) ;;
  esac

  if ! _check_user "${_to_user}"; then
    return 1
  fi

  if ! _check_user "${_from_user}"; then
    return 1
  fi

  # Grant facl for controller/joystick
  _grant_joystick || {
    return 1
  }

  _execute "${_from_user}" "${_to_user}" "$@" || return 1
  return 0
}

main "$@" || exit 1
exit 0
