#!/bin/bash
# shellcheck shell=bash

# bash completion support for containers script
__containers() {
  COMPREPLY=()
  local prev="${COMP_WORDS[COMP_CWORD - 1]}"
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local commands="ps logs images inspect reload disable restart status stop checkup enter prune pull teardown"

  _reply() {
    # shellcheck disable=SC2207
    COMPREPLY=($(compgen -W "$1" -- "$2"))
  }

  _select() {
    case "$1" in
    ps | pull | checkup | prune | reload)
      # No further arguments
      COMPREPLY=()
      ;;
    logs | images | inspect | enter | teardown | disable | restart | status | stop)
      # Offer contains
      _reply "$(containers ps --noheading --format '{{ .Names }}')" "$3"
      ;;
    *)
      # Nothing, fill with suggestions
      _reply "$2" "$3"
      ;;
    esac
  }

  _strip() {
    printf -- '%s' "$1" | tr -d '[:space:]'
  }

  if [ "${COMP_CWORD}" -le 1 ]; then
    # Not enough commands, default
    _reply "${commands}" "${cur}"
    return
  fi

  if [ -n "${prev}" ]; then
    local _previous
    _previous="$(_strip "${prev}")"

    if [ -n "${_previous}" ]; then
      _select "${_previous}" "${commands}" "${cur}"
      return
    fi
  fi

  if [ -n "${cur}" ]; then
    local _current
    _current="$(_strip "${cur}")"

    if [ -n "${_current}" ]; then
      _select "${_current}" "${commands}" "${cur}"
      return
    fi
  fi

  # Nothing at all, fill with suggestions
  _reply "${commands}" "${cur}"
}

complete -o bashdefault -o default -o nospace -F __containers containers
