#!/bin/sh

_target_user="$(basename "$0")"
readonly _target_user

_check_user() {
  if ! id -u "${_target_user}" >/dev/null 2>&1; then
    printf -- 'Target user %s does not exist!\n' "${_target_user}"
    return 1
  fi

  return 0
}

main() {
  if ! _check_user; then
    return 1
  fi

  # If the first argument is "shell", we want to instead execute container-runas
  if [ -n "$1" ] && [ "$1" = "shell" ]; then
    # Eat the "shell" argument
    shift

    # Instead execute container-runas
    exec "${HOME}/bin/container-runas" "${_target_user#containers-}" "$@"
  else
    exec sudo -u "${_target_user}" /opt/pyamsoft/bin/container-delegate "$@"
  fi
}

main "$@" || exit 1
exit 0
